// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.7
// source: cmd/cmd_sign_in.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OpActivityTagBriefInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConfigId       uint32 `protobuf:"varint,2,opt,name=config_id,json=configId,proto3" json:"config_id,omitempty"`
	HasReward      bool   `protobuf:"varint,3,opt,name=has_reward,json=hasReward,proto3" json:"has_reward,omitempty"`
	OpActivityType uint32 `protobuf:"varint,11,opt,name=op_activity_type,json=opActivityType,proto3" json:"op_activity_type,omitempty"`
}

func (x *OpActivityTagBriefInfo) Reset() {
	*x = OpActivityTagBriefInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_cmd_sign_in_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpActivityTagBriefInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpActivityTagBriefInfo) ProtoMessage() {}

func (x *OpActivityTagBriefInfo) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_cmd_sign_in_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpActivityTagBriefInfo.ProtoReflect.Descriptor instead.
func (*OpActivityTagBriefInfo) Descriptor() ([]byte, []int) {
	return file_cmd_cmd_sign_in_proto_rawDescGZIP(), []int{0}
}

func (x *OpActivityTagBriefInfo) GetConfigId() uint32 {
	if x != nil {
		return x.ConfigId
	}
	return 0
}

func (x *OpActivityTagBriefInfo) GetHasReward() bool {
	if x != nil {
		return x.HasReward
	}
	return false
}

func (x *OpActivityTagBriefInfo) GetOpActivityType() uint32 {
	if x != nil {
		return x.OpActivityType
	}
	return 0
}

type OpActivityStateNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FinishedBonusActivityIdList []uint32                  `protobuf:"varint,14,rep,packed,name=finished_bonus_activity_id_list,json=finishedBonusActivityIdList,proto3" json:"finished_bonus_activity_id_list,omitempty"`
	OpenedOpActivityInfoList    []*OpActivityTagBriefInfo `protobuf:"bytes,13,rep,name=opened_op_activity_info_list,json=openedOpActivityInfoList,proto3" json:"opened_op_activity_info_list,omitempty"`
}

func (x *OpActivityStateNotify) Reset() {
	*x = OpActivityStateNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_cmd_sign_in_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpActivityStateNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpActivityStateNotify) ProtoMessage() {}

func (x *OpActivityStateNotify) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_cmd_sign_in_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpActivityStateNotify.ProtoReflect.Descriptor instead.
func (*OpActivityStateNotify) Descriptor() ([]byte, []int) {
	return file_cmd_cmd_sign_in_proto_rawDescGZIP(), []int{1}
}

func (x *OpActivityStateNotify) GetFinishedBonusActivityIdList() []uint32 {
	if x != nil {
		return x.FinishedBonusActivityIdList
	}
	return nil
}

func (x *OpActivityStateNotify) GetOpenedOpActivityInfoList() []*OpActivityTagBriefInfo {
	if x != nil {
		return x.OpenedOpActivityInfoList
	}
	return nil
}

type SignInData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DayCount       uint32       `protobuf:"varint,14,opt,name=day_count,json=dayCount,proto3" json:"day_count,omitempty"`
	RewardItemList []*ItemParam `protobuf:"bytes,5,rep,name=reward_item_list,json=rewardItemList,proto3" json:"reward_item_list,omitempty"`
}

func (x *SignInData) Reset() {
	*x = SignInData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_cmd_sign_in_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignInData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignInData) ProtoMessage() {}

func (x *SignInData) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_cmd_sign_in_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignInData.ProtoReflect.Descriptor instead.
func (*SignInData) Descriptor() ([]byte, []int) {
	return file_cmd_cmd_sign_in_proto_rawDescGZIP(), []int{2}
}

func (x *SignInData) GetDayCount() uint32 {
	if x != nil {
		return x.DayCount
	}
	return 0
}

func (x *SignInData) GetRewardItemList() []*ItemParam {
	if x != nil {
		return x.RewardItemList
	}
	return nil
}

type SignInInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsCondSatisfied bool          `protobuf:"varint,7,opt,name=is_cond_satisfied,json=isCondSatisfied,proto3" json:"is_cond_satisfied,omitempty"`
	RewardDayList   []uint32      `protobuf:"varint,15,rep,packed,name=reward_day_list,json=rewardDayList,proto3" json:"reward_day_list,omitempty"`
	SigninDataList  []*SignInData `protobuf:"bytes,12,rep,name=signin_data_list,json=signinDataList,proto3" json:"signin_data_list,omitempty"`
	ConfigId        uint32        `protobuf:"varint,8,opt,name=config_id,json=configId,proto3" json:"config_id,omitempty"`
	SignInCount     uint32        `protobuf:"varint,2,opt,name=sign_in_count,json=signInCount,proto3" json:"sign_in_count,omitempty"`
	ScheduleId      uint32        `protobuf:"varint,3,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"`
	EndTime         uint32        `protobuf:"varint,13,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	LastSignInTime  uint32        `protobuf:"varint,6,opt,name=last_sign_in_time,json=lastSignInTime,proto3" json:"last_sign_in_time,omitempty"`
	BeginTime       uint32        `protobuf:"varint,5,opt,name=begin_time,json=beginTime,proto3" json:"begin_time,omitempty"`
}

func (x *SignInInfo) Reset() {
	*x = SignInInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_cmd_sign_in_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignInInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignInInfo) ProtoMessage() {}

func (x *SignInInfo) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_cmd_sign_in_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignInInfo.ProtoReflect.Descriptor instead.
func (*SignInInfo) Descriptor() ([]byte, []int) {
	return file_cmd_cmd_sign_in_proto_rawDescGZIP(), []int{3}
}

func (x *SignInInfo) GetIsCondSatisfied() bool {
	if x != nil {
		return x.IsCondSatisfied
	}
	return false
}

func (x *SignInInfo) GetRewardDayList() []uint32 {
	if x != nil {
		return x.RewardDayList
	}
	return nil
}

func (x *SignInInfo) GetSigninDataList() []*SignInData {
	if x != nil {
		return x.SigninDataList
	}
	return nil
}

func (x *SignInInfo) GetConfigId() uint32 {
	if x != nil {
		return x.ConfigId
	}
	return 0
}

func (x *SignInInfo) GetSignInCount() uint32 {
	if x != nil {
		return x.SignInCount
	}
	return 0
}

func (x *SignInInfo) GetScheduleId() uint32 {
	if x != nil {
		return x.ScheduleId
	}
	return 0
}

func (x *SignInInfo) GetEndTime() uint32 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *SignInInfo) GetLastSignInTime() uint32 {
	if x != nil {
		return x.LastSignInTime
	}
	return 0
}

func (x *SignInInfo) GetBeginTime() uint32 {
	if x != nil {
		return x.BeginTime
	}
	return 0
}

type SignInInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SignInInfoReq) Reset() {
	*x = SignInInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_cmd_sign_in_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignInInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignInInfoReq) ProtoMessage() {}

func (x *SignInInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_cmd_sign_in_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignInInfoReq.ProtoReflect.Descriptor instead.
func (*SignInInfoReq) Descriptor() ([]byte, []int) {
	return file_cmd_cmd_sign_in_proto_rawDescGZIP(), []int{4}
}

type SignInInfoRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SignInInfoList []*SignInInfo `protobuf:"bytes,1,rep,name=sign_in_info_list,json=signInInfoList,proto3" json:"sign_in_info_list,omitempty"`
	Retcode        int32         `protobuf:"varint,11,opt,name=retcode,proto3" json:"retcode,omitempty"`
}

func (x *SignInInfoRsp) Reset() {
	*x = SignInInfoRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_cmd_sign_in_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignInInfoRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignInInfoRsp) ProtoMessage() {}

func (x *SignInInfoRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_cmd_sign_in_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignInInfoRsp.ProtoReflect.Descriptor instead.
func (*SignInInfoRsp) Descriptor() ([]byte, []int) {
	return file_cmd_cmd_sign_in_proto_rawDescGZIP(), []int{5}
}

func (x *SignInInfoRsp) GetSignInInfoList() []*SignInInfo {
	if x != nil {
		return x.SignInInfoList
	}
	return nil
}

func (x *SignInInfoRsp) GetRetcode() int32 {
	if x != nil {
		return x.Retcode
	}
	return 0
}

type GetSignInRewardReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ScheduleId uint32 `protobuf:"varint,10,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"`
	RewardDay  uint32 `protobuf:"varint,3,opt,name=reward_day,json=rewardDay,proto3" json:"reward_day,omitempty"`
}

func (x *GetSignInRewardReq) Reset() {
	*x = GetSignInRewardReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_cmd_sign_in_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSignInRewardReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSignInRewardReq) ProtoMessage() {}

func (x *GetSignInRewardReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_cmd_sign_in_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSignInRewardReq.ProtoReflect.Descriptor instead.
func (*GetSignInRewardReq) Descriptor() ([]byte, []int) {
	return file_cmd_cmd_sign_in_proto_rawDescGZIP(), []int{6}
}

func (x *GetSignInRewardReq) GetScheduleId() uint32 {
	if x != nil {
		return x.ScheduleId
	}
	return 0
}

func (x *GetSignInRewardReq) GetRewardDay() uint32 {
	if x != nil {
		return x.RewardDay
	}
	return 0
}

type GetSignInRewardRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Retcode    int32       `protobuf:"varint,1,opt,name=retcode,proto3" json:"retcode,omitempty"`
	SignInInfo *SignInInfo `protobuf:"bytes,14,opt,name=sign_in_info,json=signInInfo,proto3" json:"sign_in_info,omitempty"`
}

func (x *GetSignInRewardRsp) Reset() {
	*x = GetSignInRewardRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_cmd_sign_in_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSignInRewardRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSignInRewardRsp) ProtoMessage() {}

func (x *GetSignInRewardRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_cmd_sign_in_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSignInRewardRsp.ProtoReflect.Descriptor instead.
func (*GetSignInRewardRsp) Descriptor() ([]byte, []int) {
	return file_cmd_cmd_sign_in_proto_rawDescGZIP(), []int{7}
}

func (x *GetSignInRewardRsp) GetRetcode() int32 {
	if x != nil {
		return x.Retcode
	}
	return 0
}

func (x *GetSignInRewardRsp) GetSignInInfo() *SignInInfo {
	if x != nil {
		return x.SignInInfo
	}
	return nil
}

type BonusActivityInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BonusActivityId uint32 `protobuf:"varint,6,opt,name=bonus_activity_id,json=bonusActivityId,proto3" json:"bonus_activity_id,omitempty"`
	State           uint32 `protobuf:"varint,3,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *BonusActivityInfo) Reset() {
	*x = BonusActivityInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_cmd_sign_in_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BonusActivityInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BonusActivityInfo) ProtoMessage() {}

func (x *BonusActivityInfo) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_cmd_sign_in_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BonusActivityInfo.ProtoReflect.Descriptor instead.
func (*BonusActivityInfo) Descriptor() ([]byte, []int) {
	return file_cmd_cmd_sign_in_proto_rawDescGZIP(), []int{8}
}

func (x *BonusActivityInfo) GetBonusActivityId() uint32 {
	if x != nil {
		return x.BonusActivityId
	}
	return 0
}

func (x *BonusActivityInfo) GetState() uint32 {
	if x != nil {
		return x.State
	}
	return 0
}

type BonusActivityUpdateNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BonusActivityInfoList []*BonusActivityInfo `protobuf:"bytes,8,rep,name=bonus_activity_info_list,json=bonusActivityInfoList,proto3" json:"bonus_activity_info_list,omitempty"`
}

func (x *BonusActivityUpdateNotify) Reset() {
	*x = BonusActivityUpdateNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_cmd_sign_in_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BonusActivityUpdateNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BonusActivityUpdateNotify) ProtoMessage() {}

func (x *BonusActivityUpdateNotify) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_cmd_sign_in_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BonusActivityUpdateNotify.ProtoReflect.Descriptor instead.
func (*BonusActivityUpdateNotify) Descriptor() ([]byte, []int) {
	return file_cmd_cmd_sign_in_proto_rawDescGZIP(), []int{9}
}

func (x *BonusActivityUpdateNotify) GetBonusActivityInfoList() []*BonusActivityInfo {
	if x != nil {
		return x.BonusActivityInfoList
	}
	return nil
}

type BonusActivityInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BonusActivityInfoReq) Reset() {
	*x = BonusActivityInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_cmd_sign_in_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BonusActivityInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BonusActivityInfoReq) ProtoMessage() {}

func (x *BonusActivityInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_cmd_sign_in_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BonusActivityInfoReq.ProtoReflect.Descriptor instead.
func (*BonusActivityInfoReq) Descriptor() ([]byte, []int) {
	return file_cmd_cmd_sign_in_proto_rawDescGZIP(), []int{10}
}

type BonusActivityInfoRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BonusActivityInfoList []*BonusActivityInfo `protobuf:"bytes,2,rep,name=bonus_activity_info_list,json=bonusActivityInfoList,proto3" json:"bonus_activity_info_list,omitempty"`
	Retcode               int32                `protobuf:"varint,7,opt,name=retcode,proto3" json:"retcode,omitempty"`
}

func (x *BonusActivityInfoRsp) Reset() {
	*x = BonusActivityInfoRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_cmd_sign_in_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BonusActivityInfoRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BonusActivityInfoRsp) ProtoMessage() {}

func (x *BonusActivityInfoRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_cmd_sign_in_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BonusActivityInfoRsp.ProtoReflect.Descriptor instead.
func (*BonusActivityInfoRsp) Descriptor() ([]byte, []int) {
	return file_cmd_cmd_sign_in_proto_rawDescGZIP(), []int{11}
}

func (x *BonusActivityInfoRsp) GetBonusActivityInfoList() []*BonusActivityInfo {
	if x != nil {
		return x.BonusActivityInfoList
	}
	return nil
}

func (x *BonusActivityInfoRsp) GetRetcode() int32 {
	if x != nil {
		return x.Retcode
	}
	return 0
}

type GetBonusActivityRewardReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BonusActivityId uint32 `protobuf:"varint,14,opt,name=bonus_activity_id,json=bonusActivityId,proto3" json:"bonus_activity_id,omitempty"`
}

func (x *GetBonusActivityRewardReq) Reset() {
	*x = GetBonusActivityRewardReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_cmd_sign_in_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBonusActivityRewardReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBonusActivityRewardReq) ProtoMessage() {}

func (x *GetBonusActivityRewardReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_cmd_sign_in_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBonusActivityRewardReq.ProtoReflect.Descriptor instead.
func (*GetBonusActivityRewardReq) Descriptor() ([]byte, []int) {
	return file_cmd_cmd_sign_in_proto_rawDescGZIP(), []int{12}
}

func (x *GetBonusActivityRewardReq) GetBonusActivityId() uint32 {
	if x != nil {
		return x.BonusActivityId
	}
	return 0
}

type GetBonusActivityRewardRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BonusActivityInfoList *BonusActivityInfo `protobuf:"bytes,4,opt,name=bonus_activity_info_list,json=bonusActivityInfoList,proto3" json:"bonus_activity_info_list,omitempty"`
	Retcode               int32              `protobuf:"varint,13,opt,name=retcode,proto3" json:"retcode,omitempty"`
}

func (x *GetBonusActivityRewardRsp) Reset() {
	*x = GetBonusActivityRewardRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_cmd_sign_in_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBonusActivityRewardRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBonusActivityRewardRsp) ProtoMessage() {}

func (x *GetBonusActivityRewardRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_cmd_sign_in_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBonusActivityRewardRsp.ProtoReflect.Descriptor instead.
func (*GetBonusActivityRewardRsp) Descriptor() ([]byte, []int) {
	return file_cmd_cmd_sign_in_proto_rawDescGZIP(), []int{13}
}

func (x *GetBonusActivityRewardRsp) GetBonusActivityInfoList() *BonusActivityInfo {
	if x != nil {
		return x.BonusActivityInfoList
	}
	return nil
}

func (x *GetBonusActivityRewardRsp) GetRetcode() int32 {
	if x != nil {
		return x.Retcode
	}
	return 0
}

var File_cmd_cmd_sign_in_proto protoreflect.FileDescriptor

var file_cmd_cmd_sign_in_proto_rawDesc = []byte{
	0x0a, 0x15, 0x63, 0x6d, 0x64, 0x2f, 0x63, 0x6d, 0x64, 0x5f, 0x73, 0x69, 0x67, 0x6e, 0x5f, 0x69,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0c,
	0x64, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7e, 0x0a, 0x16,
	0x4f, 0x70, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x54, 0x61, 0x67, 0x42, 0x72, 0x69,
	0x65, 0x66, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x68, 0x61, 0x73, 0x5f, 0x72, 0x65, 0x77, 0x61, 0x72,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x68, 0x61, 0x73, 0x52, 0x65, 0x77, 0x61,
	0x72, 0x64, 0x12, 0x28, 0x0a, 0x10, 0x6f, 0x70, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74,
	0x79, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0e, 0x6f, 0x70,
	0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x54, 0x79, 0x70, 0x65, 0x22, 0xbc, 0x01, 0x0a,
	0x15, 0x4f, 0x70, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x44, 0x0a, 0x1f, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68,
	0x65, 0x64, 0x5f, 0x62, 0x6f, 0x6e, 0x75, 0x73, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74,
	0x79, 0x5f, 0x69, 0x64, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x0e, 0x20, 0x03, 0x28, 0x0d, 0x52,
	0x1b, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x42, 0x6f, 0x6e, 0x75, 0x73, 0x41, 0x63,
	0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x5d, 0x0a, 0x1c,
	0x6f, 0x70, 0x65, 0x6e, 0x65, 0x64, 0x5f, 0x6f, 0x70, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69,
	0x74, 0x79, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x0d, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4f, 0x70, 0x41, 0x63, 0x74,
	0x69, 0x76, 0x69, 0x74, 0x79, 0x54, 0x61, 0x67, 0x42, 0x72, 0x69, 0x65, 0x66, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x18, 0x6f, 0x70, 0x65, 0x6e, 0x65, 0x64, 0x4f, 0x70, 0x41, 0x63, 0x74, 0x69, 0x76,
	0x69, 0x74, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x65, 0x0a, 0x0a, 0x53,
	0x69, 0x67, 0x6e, 0x49, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x61, 0x79,
	0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x64, 0x61,
	0x79, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x3a, 0x0a, 0x10, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64,
	0x5f, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x52, 0x0e, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x4c, 0x69,
	0x73, 0x74, 0x22, 0xe4, 0x02, 0x0a, 0x0a, 0x53, 0x69, 0x67, 0x6e, 0x49, 0x6e, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x2a, 0x0a, 0x11, 0x69, 0x73, 0x5f, 0x63, 0x6f, 0x6e, 0x64, 0x5f, 0x73, 0x61, 0x74,
	0x69, 0x73, 0x66, 0x69, 0x65, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0f, 0x69, 0x73,
	0x43, 0x6f, 0x6e, 0x64, 0x53, 0x61, 0x74, 0x69, 0x73, 0x66, 0x69, 0x65, 0x64, 0x12, 0x26, 0x0a,
	0x0f, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x5f, 0x64, 0x61, 0x79, 0x5f, 0x6c, 0x69, 0x73, 0x74,
	0x18, 0x0f, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x0d, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x44, 0x61,
	0x79, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x3b, 0x0a, 0x10, 0x73, 0x69, 0x67, 0x6e, 0x69, 0x6e, 0x5f,
	0x64, 0x61, 0x74, 0x61, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x0c, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x49, 0x6e, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x0e, 0x73, 0x69, 0x67, 0x6e, 0x69, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x5f, 0x69, 0x64, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x64, 0x12,
	0x22, 0x0a, 0x0d, 0x73, 0x69, 0x67, 0x6e, 0x5f, 0x69, 0x6e, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x73, 0x69, 0x67, 0x6e, 0x49, 0x6e, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75,
	0x6c, 0x65, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65,
	0x18, 0x0d, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12,
	0x29, 0x0a, 0x11, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x73, 0x69, 0x67, 0x6e, 0x5f, 0x69, 0x6e, 0x5f,
	0x74, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0e, 0x6c, 0x61, 0x73, 0x74,
	0x53, 0x69, 0x67, 0x6e, 0x49, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x65,
	0x67, 0x69, 0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09,
	0x62, 0x65, 0x67, 0x69, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x0f, 0x0a, 0x0d, 0x53, 0x69, 0x67,
	0x6e, 0x49, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x22, 0x67, 0x0a, 0x0d, 0x53, 0x69,
	0x67, 0x6e, 0x49, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x73, 0x70, 0x12, 0x3c, 0x0a, 0x11, 0x73,
	0x69, 0x67, 0x6e, 0x5f, 0x69, 0x6e, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x5f, 0x6c, 0x69, 0x73, 0x74,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53,
	0x69, 0x67, 0x6e, 0x49, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0e, 0x73, 0x69, 0x67, 0x6e, 0x49,
	0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x74,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x72, 0x65, 0x74, 0x63,
	0x6f, 0x64, 0x65, 0x22, 0x54, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x53, 0x69, 0x67, 0x6e, 0x49, 0x6e,
	0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x63, 0x68,
	0x65, 0x64, 0x75, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a,
	0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65,
	0x77, 0x61, 0x72, 0x64, 0x5f, 0x64, 0x61, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09,
	0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x44, 0x61, 0x79, 0x22, 0x63, 0x0a, 0x12, 0x47, 0x65, 0x74,
	0x53, 0x69, 0x67, 0x6e, 0x49, 0x6e, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x52, 0x73, 0x70, 0x12,
	0x18, 0x0a, 0x07, 0x72, 0x65, 0x74, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x07, 0x72, 0x65, 0x74, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x33, 0x0a, 0x0c, 0x73, 0x69, 0x67,
	0x6e, 0x5f, 0x69, 0x6e, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x49, 0x6e, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x0a, 0x73, 0x69, 0x67, 0x6e, 0x49, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x55,
	0x0a, 0x11, 0x42, 0x6f, 0x6e, 0x75, 0x73, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x2a, 0x0a, 0x11, 0x62, 0x6f, 0x6e, 0x75, 0x73, 0x5f, 0x61, 0x63, 0x74,
	0x69, 0x76, 0x69, 0x74, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0f,
	0x62, 0x6f, 0x6e, 0x75, 0x73, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x6e, 0x0a, 0x19, 0x42, 0x6f, 0x6e, 0x75, 0x73, 0x41, 0x63,
	0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4e, 0x6f, 0x74, 0x69,
	0x66, 0x79, 0x12, 0x51, 0x0a, 0x18, 0x62, 0x6f, 0x6e, 0x75, 0x73, 0x5f, 0x61, 0x63, 0x74, 0x69,
	0x76, 0x69, 0x74, 0x79, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x08,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x6f, 0x6e,
	0x75, 0x73, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x15,
	0x62, 0x6f, 0x6e, 0x75, 0x73, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x6e, 0x66,
	0x6f, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x16, 0x0a, 0x14, 0x42, 0x6f, 0x6e, 0x75, 0x73, 0x41, 0x63,
	0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x22, 0x83, 0x01,
	0x0a, 0x14, 0x42, 0x6f, 0x6e, 0x75, 0x73, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x73, 0x70, 0x12, 0x51, 0x0a, 0x18, 0x62, 0x6f, 0x6e, 0x75, 0x73, 0x5f,
	0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x5f, 0x6c, 0x69,
	0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x42, 0x6f, 0x6e, 0x75, 0x73, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x15, 0x62, 0x6f, 0x6e, 0x75, 0x73, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74,
	0x79, 0x49, 0x6e, 0x66, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x74,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x72, 0x65, 0x74, 0x63,
	0x6f, 0x64, 0x65, 0x22, 0x47, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x6e, 0x75, 0x73, 0x41,
	0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71,
	0x12, 0x2a, 0x0a, 0x11, 0x62, 0x6f, 0x6e, 0x75, 0x73, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69,
	0x74, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0f, 0x62, 0x6f, 0x6e,
	0x75, 0x73, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x64, 0x22, 0x88, 0x01, 0x0a,
	0x19, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x6e, 0x75, 0x73, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74,
	0x79, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x52, 0x73, 0x70, 0x12, 0x51, 0x0a, 0x18, 0x62, 0x6f,
	0x6e, 0x75, 0x73, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x5f, 0x69, 0x6e, 0x66,
	0x6f, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x6f, 0x6e, 0x75, 0x73, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69,
	0x74, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x15, 0x62, 0x6f, 0x6e, 0x75, 0x73, 0x41, 0x63, 0x74,
	0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x72, 0x65, 0x74, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07,
	0x72, 0x65, 0x74, 0x63, 0x6f, 0x64, 0x65, 0x42, 0x28, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x65, 0x79, 0x76, 0x61, 0x74, 0x2d, 0x68, 0x65, 0x6c,
	0x70, 0x65, 0x72, 0x2f, 0x68, 0x6b, 0x34, 0x65, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cmd_cmd_sign_in_proto_rawDescOnce sync.Once
	file_cmd_cmd_sign_in_proto_rawDescData = file_cmd_cmd_sign_in_proto_rawDesc
)

func file_cmd_cmd_sign_in_proto_rawDescGZIP() []byte {
	file_cmd_cmd_sign_in_proto_rawDescOnce.Do(func() {
		file_cmd_cmd_sign_in_proto_rawDescData = protoimpl.X.CompressGZIP(file_cmd_cmd_sign_in_proto_rawDescData)
	})
	return file_cmd_cmd_sign_in_proto_rawDescData
}

var file_cmd_cmd_sign_in_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_cmd_cmd_sign_in_proto_goTypes = []interface{}{
	(*OpActivityTagBriefInfo)(nil),    // 0: proto.OpActivityTagBriefInfo
	(*OpActivityStateNotify)(nil),     // 1: proto.OpActivityStateNotify
	(*SignInData)(nil),                // 2: proto.SignInData
	(*SignInInfo)(nil),                // 3: proto.SignInInfo
	(*SignInInfoReq)(nil),             // 4: proto.SignInInfoReq
	(*SignInInfoRsp)(nil),             // 5: proto.SignInInfoRsp
	(*GetSignInRewardReq)(nil),        // 6: proto.GetSignInRewardReq
	(*GetSignInRewardRsp)(nil),        // 7: proto.GetSignInRewardRsp
	(*BonusActivityInfo)(nil),         // 8: proto.BonusActivityInfo
	(*BonusActivityUpdateNotify)(nil), // 9: proto.BonusActivityUpdateNotify
	(*BonusActivityInfoReq)(nil),      // 10: proto.BonusActivityInfoReq
	(*BonusActivityInfoRsp)(nil),      // 11: proto.BonusActivityInfoRsp
	(*GetBonusActivityRewardReq)(nil), // 12: proto.GetBonusActivityRewardReq
	(*GetBonusActivityRewardRsp)(nil), // 13: proto.GetBonusActivityRewardRsp
	(*ItemParam)(nil),                 // 14: proto.ItemParam
}
var file_cmd_cmd_sign_in_proto_depIdxs = []int32{
	0,  // 0: proto.OpActivityStateNotify.opened_op_activity_info_list:type_name -> proto.OpActivityTagBriefInfo
	14, // 1: proto.SignInData.reward_item_list:type_name -> proto.ItemParam
	2,  // 2: proto.SignInInfo.signin_data_list:type_name -> proto.SignInData
	3,  // 3: proto.SignInInfoRsp.sign_in_info_list:type_name -> proto.SignInInfo
	3,  // 4: proto.GetSignInRewardRsp.sign_in_info:type_name -> proto.SignInInfo
	8,  // 5: proto.BonusActivityUpdateNotify.bonus_activity_info_list:type_name -> proto.BonusActivityInfo
	8,  // 6: proto.BonusActivityInfoRsp.bonus_activity_info_list:type_name -> proto.BonusActivityInfo
	8,  // 7: proto.GetBonusActivityRewardRsp.bonus_activity_info_list:type_name -> proto.BonusActivityInfo
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_cmd_cmd_sign_in_proto_init() }
func file_cmd_cmd_sign_in_proto_init() {
	if File_cmd_cmd_sign_in_proto != nil {
		return
	}
	file_define_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_cmd_cmd_sign_in_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpActivityTagBriefInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_cmd_sign_in_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpActivityStateNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_cmd_sign_in_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignInData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_cmd_sign_in_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignInInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_cmd_sign_in_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignInInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_cmd_sign_in_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignInInfoRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_cmd_sign_in_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSignInRewardReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_cmd_sign_in_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSignInRewardRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_cmd_sign_in_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BonusActivityInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_cmd_sign_in_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BonusActivityUpdateNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_cmd_sign_in_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BonusActivityInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_cmd_sign_in_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BonusActivityInfoRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_cmd_sign_in_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBonusActivityRewardReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_cmd_sign_in_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBonusActivityRewardRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cmd_cmd_sign_in_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cmd_cmd_sign_in_proto_goTypes,
		DependencyIndexes: file_cmd_cmd_sign_in_proto_depIdxs,
		MessageInfos:      file_cmd_cmd_sign_in_proto_msgTypes,
	}.Build()
	File_cmd_cmd_sign_in_proto = out.File
	file_cmd_cmd_sign_in_proto_rawDesc = nil
	file_cmd_cmd_sign_in_proto_goTypes = nil
	file_cmd_cmd_sign_in_proto_depIdxs = nil
}
