// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.7
// source: server_only/cmd_player.server.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayerOnlineStatusInfo_StatusType int32

const (
	PlayerOnlineStatusInfo_ONLINE  PlayerOnlineStatusInfo_StatusType = 0
	PlayerOnlineStatusInfo_OFFLINE PlayerOnlineStatusInfo_StatusType = 1
)

// Enum value maps for PlayerOnlineStatusInfo_StatusType.
var (
	PlayerOnlineStatusInfo_StatusType_name = map[int32]string{
		0: "ONLINE",
		1: "OFFLINE",
	}
	PlayerOnlineStatusInfo_StatusType_value = map[string]int32{
		"ONLINE":  0,
		"OFFLINE": 1,
	}
)

func (x PlayerOnlineStatusInfo_StatusType) Enum() *PlayerOnlineStatusInfo_StatusType {
	p := new(PlayerOnlineStatusInfo_StatusType)
	*p = x
	return p
}

func (x PlayerOnlineStatusInfo_StatusType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlayerOnlineStatusInfo_StatusType) Descriptor() protoreflect.EnumDescriptor {
	return file_server_only_cmd_player_server_proto_enumTypes[0].Descriptor()
}

func (PlayerOnlineStatusInfo_StatusType) Type() protoreflect.EnumType {
	return &file_server_only_cmd_player_server_proto_enumTypes[0]
}

func (x PlayerOnlineStatusInfo_StatusType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlayerOnlineStatusInfo_StatusType.Descriptor instead.
func (PlayerOnlineStatusInfo_StatusType) EnumDescriptor() ([]byte, []int) {
	return file_server_only_cmd_player_server_proto_rawDescGZIP(), []int{2, 0}
}

type SavePlayerDataReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerData *PlayerData `protobuf:"bytes,1,opt,name=player_data,json=playerData,proto3" json:"player_data,omitempty"`
	SaveStatId uint32      `protobuf:"varint,2,opt,name=save_stat_id,json=saveStatId,proto3" json:"save_stat_id,omitempty"`
}

func (x *SavePlayerDataReq) Reset() {
	*x = SavePlayerDataReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_only_cmd_player_server_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SavePlayerDataReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SavePlayerDataReq) ProtoMessage() {}

func (x *SavePlayerDataReq) ProtoReflect() protoreflect.Message {
	mi := &file_server_only_cmd_player_server_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SavePlayerDataReq.ProtoReflect.Descriptor instead.
func (*SavePlayerDataReq) Descriptor() ([]byte, []int) {
	return file_server_only_cmd_player_server_proto_rawDescGZIP(), []int{0}
}

func (x *SavePlayerDataReq) GetPlayerData() *PlayerData {
	if x != nil {
		return x.PlayerData
	}
	return nil
}

func (x *SavePlayerDataReq) GetSaveStatId() uint32 {
	if x != nil {
		return x.SaveStatId
	}
	return 0
}

type SavePlayerDataRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Retcode     int32  `protobuf:"varint,1,opt,name=retcode,proto3" json:"retcode,omitempty"`
	DataVersion uint32 `protobuf:"varint,2,opt,name=data_version,json=dataVersion,proto3" json:"data_version,omitempty"`
	SaveStatId  uint32 `protobuf:"varint,3,opt,name=save_stat_id,json=saveStatId,proto3" json:"save_stat_id,omitempty"`
}

func (x *SavePlayerDataRsp) Reset() {
	*x = SavePlayerDataRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_only_cmd_player_server_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SavePlayerDataRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SavePlayerDataRsp) ProtoMessage() {}

func (x *SavePlayerDataRsp) ProtoReflect() protoreflect.Message {
	mi := &file_server_only_cmd_player_server_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SavePlayerDataRsp.ProtoReflect.Descriptor instead.
func (*SavePlayerDataRsp) Descriptor() ([]byte, []int) {
	return file_server_only_cmd_player_server_proto_rawDescGZIP(), []int{1}
}

func (x *SavePlayerDataRsp) GetRetcode() int32 {
	if x != nil {
		return x.Retcode
	}
	return 0
}

func (x *SavePlayerDataRsp) GetDataVersion() uint32 {
	if x != nil {
		return x.DataVersion
	}
	return 0
}

func (x *SavePlayerDataRsp) GetSaveStatId() uint32 {
	if x != nil {
		return x.SaveStatId
	}
	return 0
}

type PlayerOnlineStatusInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid          uint32                            `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	PlatformType uint32                            `protobuf:"varint,2,opt,name=platform_type,json=platformType,proto3" json:"platform_type,omitempty"`
	OnlineStatus PlayerOnlineStatusInfo_StatusType `protobuf:"varint,3,opt,name=online_status,json=onlineStatus,proto3,enum=proto.PlayerOnlineStatusInfo_StatusType" json:"online_status,omitempty"`
	IsSubAccount bool                              `protobuf:"varint,4,opt,name=is_sub_account,json=isSubAccount,proto3" json:"is_sub_account,omitempty"`
	CountryCode  string                            `protobuf:"bytes,5,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
}

func (x *PlayerOnlineStatusInfo) Reset() {
	*x = PlayerOnlineStatusInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_only_cmd_player_server_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerOnlineStatusInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerOnlineStatusInfo) ProtoMessage() {}

func (x *PlayerOnlineStatusInfo) ProtoReflect() protoreflect.Message {
	mi := &file_server_only_cmd_player_server_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerOnlineStatusInfo.ProtoReflect.Descriptor instead.
func (*PlayerOnlineStatusInfo) Descriptor() ([]byte, []int) {
	return file_server_only_cmd_player_server_proto_rawDescGZIP(), []int{2}
}

func (x *PlayerOnlineStatusInfo) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *PlayerOnlineStatusInfo) GetPlatformType() uint32 {
	if x != nil {
		return x.PlatformType
	}
	return 0
}

func (x *PlayerOnlineStatusInfo) GetOnlineStatus() PlayerOnlineStatusInfo_StatusType {
	if x != nil {
		return x.OnlineStatus
	}
	return PlayerOnlineStatusInfo_ONLINE
}

func (x *PlayerOnlineStatusInfo) GetIsSubAccount() bool {
	if x != nil {
		return x.IsSubAccount
	}
	return false
}

func (x *PlayerOnlineStatusInfo) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

type PlayerOnlineStatusNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerInfoList []*PlayerOnlineStatusInfo `protobuf:"bytes,1,rep,name=player_info_list,json=playerInfoList,proto3" json:"player_info_list,omitempty"`
}

func (x *PlayerOnlineStatusNotify) Reset() {
	*x = PlayerOnlineStatusNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_only_cmd_player_server_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerOnlineStatusNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerOnlineStatusNotify) ProtoMessage() {}

func (x *PlayerOnlineStatusNotify) ProtoReflect() protoreflect.Message {
	mi := &file_server_only_cmd_player_server_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerOnlineStatusNotify.ProtoReflect.Descriptor instead.
func (*PlayerOnlineStatusNotify) Descriptor() ([]byte, []int) {
	return file_server_only_cmd_player_server_proto_rawDescGZIP(), []int{3}
}

func (x *PlayerOnlineStatusNotify) GetPlayerInfoList() []*PlayerOnlineStatusInfo {
	if x != nil {
		return x.PlayerInfoList
	}
	return nil
}

type ServiceDisconnectNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type ServiceType `protobuf:"varint,1,opt,name=type,proto3,enum=proto.ServiceType" json:"type,omitempty"`
	Ip   uint32      `protobuf:"varint,2,opt,name=ip,proto3" json:"ip,omitempty"`
}

func (x *ServiceDisconnectNotify) Reset() {
	*x = ServiceDisconnectNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_only_cmd_player_server_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceDisconnectNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceDisconnectNotify) ProtoMessage() {}

func (x *ServiceDisconnectNotify) ProtoReflect() protoreflect.Message {
	mi := &file_server_only_cmd_player_server_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceDisconnectNotify.ProtoReflect.Descriptor instead.
func (*ServiceDisconnectNotify) Descriptor() ([]byte, []int) {
	return file_server_only_cmd_player_server_proto_rawDescGZIP(), []int{4}
}

func (x *ServiceDisconnectNotify) GetType() ServiceType {
	if x != nil {
		return x.Type
	}
	return ServiceType_SERVICE_NONE
}

func (x *ServiceDisconnectNotify) GetIp() uint32 {
	if x != nil {
		return x.Ip
	}
	return 0
}

type PlayerDisconnectNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data uint32 `protobuf:"varint,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *PlayerDisconnectNotify) Reset() {
	*x = PlayerDisconnectNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_only_cmd_player_server_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerDisconnectNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerDisconnectNotify) ProtoMessage() {}

func (x *PlayerDisconnectNotify) ProtoReflect() protoreflect.Message {
	mi := &file_server_only_cmd_player_server_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerDisconnectNotify.ProtoReflect.Descriptor instead.
func (*PlayerDisconnectNotify) Descriptor() ([]byte, []int) {
	return file_server_only_cmd_player_server_proto_rawDescGZIP(), []int{5}
}

func (x *PlayerDisconnectNotify) GetData() uint32 {
	if x != nil {
		return x.Data
	}
	return 0
}

type DisconnectClientNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data uint32 `protobuf:"varint,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *DisconnectClientNotify) Reset() {
	*x = DisconnectClientNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_only_cmd_player_server_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DisconnectClientNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectClientNotify) ProtoMessage() {}

func (x *DisconnectClientNotify) ProtoReflect() protoreflect.Message {
	mi := &file_server_only_cmd_player_server_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectClientNotify.ProtoReflect.Descriptor instead.
func (*DisconnectClientNotify) Descriptor() ([]byte, []int) {
	return file_server_only_cmd_player_server_proto_rawDescGZIP(), []int{6}
}

func (x *DisconnectClientNotify) GetData() uint32 {
	if x != nil {
		return x.Data
	}
	return 0
}

type SysCreateGroupReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SysCreateGroupReq) Reset() {
	*x = SysCreateGroupReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_only_cmd_player_server_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SysCreateGroupReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysCreateGroupReq) ProtoMessage() {}

func (x *SysCreateGroupReq) ProtoReflect() protoreflect.Message {
	mi := &file_server_only_cmd_player_server_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysCreateGroupReq.ProtoReflect.Descriptor instead.
func (*SysCreateGroupReq) Descriptor() ([]byte, []int) {
	return file_server_only_cmd_player_server_proto_rawDescGZIP(), []int{7}
}

type SaveBlockDataReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlockInfoMap map[uint32]*BlockInfo `protobuf:"bytes,1,rep,name=block_info_map,json=blockInfoMap,proto3" json:"block_info_map,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *SaveBlockDataReq) Reset() {
	*x = SaveBlockDataReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_only_cmd_player_server_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveBlockDataReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveBlockDataReq) ProtoMessage() {}

func (x *SaveBlockDataReq) ProtoReflect() protoreflect.Message {
	mi := &file_server_only_cmd_player_server_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveBlockDataReq.ProtoReflect.Descriptor instead.
func (*SaveBlockDataReq) Descriptor() ([]byte, []int) {
	return file_server_only_cmd_player_server_proto_rawDescGZIP(), []int{8}
}

func (x *SaveBlockDataReq) GetBlockInfoMap() map[uint32]*BlockInfo {
	if x != nil {
		return x.BlockInfoMap
	}
	return nil
}

type SaveBlockDataRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Retcode          int32             `protobuf:"varint,1,opt,name=retcode,proto3" json:"retcode,omitempty"`
	BlockSuccSaveMap map[uint32]uint32 `protobuf:"bytes,2,rep,name=block_succ_save_map,json=blockSuccSaveMap,proto3" json:"block_succ_save_map,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (x *SaveBlockDataRsp) Reset() {
	*x = SaveBlockDataRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_only_cmd_player_server_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveBlockDataRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveBlockDataRsp) ProtoMessage() {}

func (x *SaveBlockDataRsp) ProtoReflect() protoreflect.Message {
	mi := &file_server_only_cmd_player_server_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveBlockDataRsp.ProtoReflect.Descriptor instead.
func (*SaveBlockDataRsp) Descriptor() ([]byte, []int) {
	return file_server_only_cmd_player_server_proto_rawDescGZIP(), []int{9}
}

func (x *SaveBlockDataRsp) GetRetcode() int32 {
	if x != nil {
		return x.Retcode
	}
	return 0
}

func (x *SaveBlockDataRsp) GetBlockSuccSaveMap() map[uint32]uint32 {
	if x != nil {
		return x.BlockSuccSaveMap
	}
	return nil
}

type SavePlayerExtraBinDataNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid                uint32 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	PlayerExtraBinData []byte `protobuf:"bytes,2,opt,name=player_extra_bin_data,json=playerExtraBinData,proto3" json:"player_extra_bin_data,omitempty"`
}

func (x *SavePlayerExtraBinDataNotify) Reset() {
	*x = SavePlayerExtraBinDataNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_only_cmd_player_server_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SavePlayerExtraBinDataNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SavePlayerExtraBinDataNotify) ProtoMessage() {}

func (x *SavePlayerExtraBinDataNotify) ProtoReflect() protoreflect.Message {
	mi := &file_server_only_cmd_player_server_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SavePlayerExtraBinDataNotify.ProtoReflect.Descriptor instead.
func (*SavePlayerExtraBinDataNotify) Descriptor() ([]byte, []int) {
	return file_server_only_cmd_player_server_proto_rawDescGZIP(), []int{10}
}

func (x *SavePlayerExtraBinDataNotify) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *SavePlayerExtraBinDataNotify) GetPlayerExtraBinData() []byte {
	if x != nil {
		return x.PlayerExtraBinData
	}
	return nil
}

type SysSavePlayerNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SysSavePlayerNotify) Reset() {
	*x = SysSavePlayerNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_only_cmd_player_server_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SysSavePlayerNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysSavePlayerNotify) ProtoMessage() {}

func (x *SysSavePlayerNotify) ProtoReflect() protoreflect.Message {
	mi := &file_server_only_cmd_player_server_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysSavePlayerNotify.ProtoReflect.Descriptor instead.
func (*SysSavePlayerNotify) Descriptor() ([]byte, []int) {
	return file_server_only_cmd_player_server_proto_rawDescGZIP(), []int{11}
}

type PlayerLoginBlockInfoNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LoginRand    uint64                `protobuf:"varint,1,opt,name=login_rand,json=loginRand,proto3" json:"login_rand,omitempty"`
	BlockInfoMap map[uint32]*BlockInfo `protobuf:"bytes,2,rep,name=block_info_map,json=blockInfoMap,proto3" json:"block_info_map,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *PlayerLoginBlockInfoNotify) Reset() {
	*x = PlayerLoginBlockInfoNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_only_cmd_player_server_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerLoginBlockInfoNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerLoginBlockInfoNotify) ProtoMessage() {}

func (x *PlayerLoginBlockInfoNotify) ProtoReflect() protoreflect.Message {
	mi := &file_server_only_cmd_player_server_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerLoginBlockInfoNotify.ProtoReflect.Descriptor instead.
func (*PlayerLoginBlockInfoNotify) Descriptor() ([]byte, []int) {
	return file_server_only_cmd_player_server_proto_rawDescGZIP(), []int{12}
}

func (x *PlayerLoginBlockInfoNotify) GetLoginRand() uint64 {
	if x != nil {
		return x.LoginRand
	}
	return 0
}

func (x *PlayerLoginBlockInfoNotify) GetBlockInfoMap() map[uint32]*BlockInfo {
	if x != nil {
		return x.BlockInfoMap
	}
	return nil
}

var File_server_only_cmd_player_server_proto protoreflect.FileDescriptor

var file_server_only_cmd_player_server_proto_rawDesc = []byte{
	0x0a, 0x23, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x6f, 0x6e, 0x6c, 0x79, 0x2f, 0x63, 0x6d,
	0x64, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x5f, 0x6f, 0x6e, 0x6c, 0x79, 0x2f, 0x62, 0x69, 0x6e, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0c, 0x64, 0x65, 0x66, 0x69,
	0x6e, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x69, 0x0a, 0x11, 0x53, 0x61, 0x76, 0x65,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x12, 0x32, 0x0a,
	0x0b, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0a, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x20, 0x0a, 0x0c, 0x73, 0x61, 0x76, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x73, 0x61, 0x76, 0x65, 0x53, 0x74, 0x61,
	0x74, 0x49, 0x64, 0x22, 0x72, 0x0a, 0x11, 0x53, 0x61, 0x76, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x44, 0x61, 0x74, 0x61, 0x52, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x74, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x72, 0x65, 0x74, 0x63, 0x6f,
	0x64, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x64, 0x61, 0x74, 0x61, 0x56, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x20, 0x0a, 0x0c, 0x73, 0x61, 0x76, 0x65, 0x5f, 0x73, 0x74,
	0x61, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x73, 0x61, 0x76,
	0x65, 0x53, 0x74, 0x61, 0x74, 0x49, 0x64, 0x22, 0x8e, 0x02, 0x0a, 0x16, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x03, 0x75, 0x69, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x70, 0x6c, 0x61,
	0x74, 0x66, 0x6f, 0x72, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x12, 0x4d, 0x0a, 0x0d, 0x6f, 0x6e, 0x6c,
	0x69, 0x6e, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x28, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4f,
	0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0c, 0x6f, 0x6e, 0x6c, 0x69,
	0x6e, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x24, 0x0a, 0x0e, 0x69, 0x73, 0x5f, 0x73,
	0x75, 0x62, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0c, 0x69, 0x73, 0x53, 0x75, 0x62, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x21,
	0x0a, 0x0c, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x43, 0x6f, 0x64,
	0x65, 0x22, 0x25, 0x0a, 0x0a, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x0a, 0x0a, 0x06, 0x4f, 0x4e, 0x4c, 0x49, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x4f,
	0x46, 0x46, 0x4c, 0x49, 0x4e, 0x45, 0x10, 0x01, 0x22, 0x63, 0x0a, 0x18, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x4e, 0x6f,
	0x74, 0x69, 0x66, 0x79, 0x12, 0x47, 0x0a, 0x10, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69,
	0x6e, 0x66, 0x6f, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4f, 0x6e, 0x6c,
	0x69, 0x6e, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0e, 0x70,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x51, 0x0a,
	0x17, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x26, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x70,
	0x22, 0x2c, 0x0a, 0x16, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x2c,
	0x0a, 0x16, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x13, 0x0a, 0x11,
	0x53, 0x79, 0x73, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65,
	0x71, 0x22, 0xb6, 0x01, 0x0a, 0x10, 0x53, 0x61, 0x76, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x12, 0x4f, 0x0a, 0x0e, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f,
	0x69, 0x6e, 0x66, 0x6f, 0x5f, 0x6d, 0x61, 0x70, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x29,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x61, 0x76, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x6e, 0x66,
	0x6f, 0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0c, 0x62, 0x6c, 0x6f, 0x63, 0x6b,
	0x49, 0x6e, 0x66, 0x6f, 0x4d, 0x61, 0x70, 0x1a, 0x51, 0x0a, 0x11, 0x42, 0x6c, 0x6f, 0x63, 0x6b,
	0x49, 0x6e, 0x66, 0x6f, 0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x26,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xcf, 0x01, 0x0a, 0x10, 0x53,
	0x61, 0x76, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x44, 0x61, 0x74, 0x61, 0x52, 0x73, 0x70, 0x12,
	0x18, 0x0a, 0x07, 0x72, 0x65, 0x74, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x07, 0x72, 0x65, 0x74, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x5c, 0x0a, 0x13, 0x62, 0x6c, 0x6f,
	0x63, 0x6b, 0x5f, 0x73, 0x75, 0x63, 0x63, 0x5f, 0x73, 0x61, 0x76, 0x65, 0x5f, 0x6d, 0x61, 0x70,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53,
	0x61, 0x76, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x44, 0x61, 0x74, 0x61, 0x52, 0x73, 0x70, 0x2e,
	0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x53, 0x75, 0x63, 0x63, 0x53, 0x61, 0x76, 0x65, 0x4d, 0x61, 0x70,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x10, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x53, 0x75, 0x63, 0x63,
	0x53, 0x61, 0x76, 0x65, 0x4d, 0x61, 0x70, 0x1a, 0x43, 0x0a, 0x15, 0x42, 0x6c, 0x6f, 0x63, 0x6b,
	0x53, 0x75, 0x63, 0x63, 0x53, 0x61, 0x76, 0x65, 0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x63, 0x0a, 0x1c,
	0x53, 0x61, 0x76, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x45, 0x78, 0x74, 0x72, 0x61, 0x42,
	0x69, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x31,
	0x0a, 0x15, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x65, 0x78, 0x74, 0x72, 0x61, 0x5f, 0x62,
	0x69, 0x6e, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x12, 0x70,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x45, 0x78, 0x74, 0x72, 0x61, 0x42, 0x69, 0x6e, 0x44, 0x61, 0x74,
	0x61, 0x22, 0x15, 0x0a, 0x13, 0x53, 0x79, 0x73, 0x53, 0x61, 0x76, 0x65, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x22, 0xe9, 0x01, 0x0a, 0x1a, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x6e, 0x66,
	0x6f, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x6c, 0x6f, 0x67, 0x69, 0x6e,
	0x5f, 0x72, 0x61, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x6c, 0x6f, 0x67,
	0x69, 0x6e, 0x52, 0x61, 0x6e, 0x64, 0x12, 0x59, 0x0a, 0x0e, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f,
	0x69, 0x6e, 0x66, 0x6f, 0x5f, 0x6d, 0x61, 0x70, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x33,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x4e, 0x6f, 0x74, 0x69, 0x66,
	0x79, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x4d, 0x61, 0x70, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x0c, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x4d, 0x61,
	0x70, 0x1a, 0x51, 0x0a, 0x11, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x4d, 0x61,
	0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x26, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x3a, 0x02, 0x38, 0x01, 0x42, 0x28, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x74, 0x65, 0x79, 0x76, 0x61, 0x74, 0x2d, 0x68, 0x65, 0x6c, 0x70, 0x65, 0x72,
	0x2f, 0x68, 0x6b, 0x34, 0x65, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_server_only_cmd_player_server_proto_rawDescOnce sync.Once
	file_server_only_cmd_player_server_proto_rawDescData = file_server_only_cmd_player_server_proto_rawDesc
)

func file_server_only_cmd_player_server_proto_rawDescGZIP() []byte {
	file_server_only_cmd_player_server_proto_rawDescOnce.Do(func() {
		file_server_only_cmd_player_server_proto_rawDescData = protoimpl.X.CompressGZIP(file_server_only_cmd_player_server_proto_rawDescData)
	})
	return file_server_only_cmd_player_server_proto_rawDescData
}

var file_server_only_cmd_player_server_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_server_only_cmd_player_server_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_server_only_cmd_player_server_proto_goTypes = []interface{}{
	(PlayerOnlineStatusInfo_StatusType)(0), // 0: proto.PlayerOnlineStatusInfo.StatusType
	(*SavePlayerDataReq)(nil),              // 1: proto.SavePlayerDataReq
	(*SavePlayerDataRsp)(nil),              // 2: proto.SavePlayerDataRsp
	(*PlayerOnlineStatusInfo)(nil),         // 3: proto.PlayerOnlineStatusInfo
	(*PlayerOnlineStatusNotify)(nil),       // 4: proto.PlayerOnlineStatusNotify
	(*ServiceDisconnectNotify)(nil),        // 5: proto.ServiceDisconnectNotify
	(*PlayerDisconnectNotify)(nil),         // 6: proto.PlayerDisconnectNotify
	(*DisconnectClientNotify)(nil),         // 7: proto.DisconnectClientNotify
	(*SysCreateGroupReq)(nil),              // 8: proto.SysCreateGroupReq
	(*SaveBlockDataReq)(nil),               // 9: proto.SaveBlockDataReq
	(*SaveBlockDataRsp)(nil),               // 10: proto.SaveBlockDataRsp
	(*SavePlayerExtraBinDataNotify)(nil),   // 11: proto.SavePlayerExtraBinDataNotify
	(*SysSavePlayerNotify)(nil),            // 12: proto.SysSavePlayerNotify
	(*PlayerLoginBlockInfoNotify)(nil),     // 13: proto.PlayerLoginBlockInfoNotify
	nil,                                    // 14: proto.SaveBlockDataReq.BlockInfoMapEntry
	nil,                                    // 15: proto.SaveBlockDataRsp.BlockSuccSaveMapEntry
	nil,                                    // 16: proto.PlayerLoginBlockInfoNotify.BlockInfoMapEntry
	(*PlayerData)(nil),                     // 17: proto.PlayerData
	(ServiceType)(0),                       // 18: proto.ServiceType
	(*BlockInfo)(nil),                      // 19: proto.BlockInfo
}
var file_server_only_cmd_player_server_proto_depIdxs = []int32{
	17, // 0: proto.SavePlayerDataReq.player_data:type_name -> proto.PlayerData
	0,  // 1: proto.PlayerOnlineStatusInfo.online_status:type_name -> proto.PlayerOnlineStatusInfo.StatusType
	3,  // 2: proto.PlayerOnlineStatusNotify.player_info_list:type_name -> proto.PlayerOnlineStatusInfo
	18, // 3: proto.ServiceDisconnectNotify.type:type_name -> proto.ServiceType
	14, // 4: proto.SaveBlockDataReq.block_info_map:type_name -> proto.SaveBlockDataReq.BlockInfoMapEntry
	15, // 5: proto.SaveBlockDataRsp.block_succ_save_map:type_name -> proto.SaveBlockDataRsp.BlockSuccSaveMapEntry
	16, // 6: proto.PlayerLoginBlockInfoNotify.block_info_map:type_name -> proto.PlayerLoginBlockInfoNotify.BlockInfoMapEntry
	19, // 7: proto.SaveBlockDataReq.BlockInfoMapEntry.value:type_name -> proto.BlockInfo
	19, // 8: proto.PlayerLoginBlockInfoNotify.BlockInfoMapEntry.value:type_name -> proto.BlockInfo
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_server_only_cmd_player_server_proto_init() }
func file_server_only_cmd_player_server_proto_init() {
	if File_server_only_cmd_player_server_proto != nil {
		return
	}
	file_server_only_bin_server_proto_init()
	file_define_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_server_only_cmd_player_server_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SavePlayerDataReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_only_cmd_player_server_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SavePlayerDataRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_only_cmd_player_server_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerOnlineStatusInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_only_cmd_player_server_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerOnlineStatusNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_only_cmd_player_server_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceDisconnectNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_only_cmd_player_server_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerDisconnectNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_only_cmd_player_server_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DisconnectClientNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_only_cmd_player_server_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SysCreateGroupReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_only_cmd_player_server_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveBlockDataReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_only_cmd_player_server_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveBlockDataRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_only_cmd_player_server_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SavePlayerExtraBinDataNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_only_cmd_player_server_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SysSavePlayerNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_only_cmd_player_server_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerLoginBlockInfoNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_server_only_cmd_player_server_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_server_only_cmd_player_server_proto_goTypes,
		DependencyIndexes: file_server_only_cmd_player_server_proto_depIdxs,
		EnumInfos:         file_server_only_cmd_player_server_proto_enumTypes,
		MessageInfos:      file_server_only_cmd_player_server_proto_msgTypes,
	}.Build()
	File_server_only_cmd_player_server_proto = out.File
	file_server_only_cmd_player_server_proto_rawDesc = nil
	file_server_only_cmd_player_server_proto_goTypes = nil
	file_server_only_cmd_player_server_proto_depIdxs = nil
}
