// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.7
// source: cmd/cmd_op_activity.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OpActivityInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActivityId  uint32 `protobuf:"varint,2,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	EndTime     uint32 `protobuf:"varint,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	BeginTime   uint32 `protobuf:"varint,5,opt,name=begin_time,json=beginTime,proto3" json:"begin_time,omitempty"`
	IsHasChange bool   `protobuf:"varint,1,opt,name=is_has_change,json=isHasChange,proto3" json:"is_has_change,omitempty"`
	ScheduleId  uint32 `protobuf:"varint,13,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"`
	// Types that are assignable to Detail:
	//
	//	*OpActivityInfo_BonusInfo
	Detail isOpActivityInfo_Detail `protobuf_oneof:"detail"`
}

func (x *OpActivityInfo) Reset() {
	*x = OpActivityInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_cmd_op_activity_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpActivityInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpActivityInfo) ProtoMessage() {}

func (x *OpActivityInfo) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_cmd_op_activity_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpActivityInfo.ProtoReflect.Descriptor instead.
func (*OpActivityInfo) Descriptor() ([]byte, []int) {
	return file_cmd_cmd_op_activity_proto_rawDescGZIP(), []int{0}
}

func (x *OpActivityInfo) GetActivityId() uint32 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *OpActivityInfo) GetEndTime() uint32 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *OpActivityInfo) GetBeginTime() uint32 {
	if x != nil {
		return x.BeginTime
	}
	return 0
}

func (x *OpActivityInfo) GetIsHasChange() bool {
	if x != nil {
		return x.IsHasChange
	}
	return false
}

func (x *OpActivityInfo) GetScheduleId() uint32 {
	if x != nil {
		return x.ScheduleId
	}
	return 0
}

func (m *OpActivityInfo) GetDetail() isOpActivityInfo_Detail {
	if m != nil {
		return m.Detail
	}
	return nil
}

func (x *OpActivityInfo) GetBonusInfo() *BonusOpActivityInfo {
	if x, ok := x.GetDetail().(*OpActivityInfo_BonusInfo); ok {
		return x.BonusInfo
	}
	return nil
}

type isOpActivityInfo_Detail interface {
	isOpActivityInfo_Detail()
}

type OpActivityInfo_BonusInfo struct {
	BonusInfo *BonusOpActivityInfo `protobuf:"bytes,12,opt,name=bonus_info,json=bonusInfo,proto3,oneof"`
}

func (*OpActivityInfo_BonusInfo) isOpActivityInfo_Detail() {}

type BonusOpActivityInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LeftBonusCount uint32 `protobuf:"varint,11,opt,name=left_bonus_count,json=leftBonusCount,proto3" json:"left_bonus_count,omitempty"`
}

func (x *BonusOpActivityInfo) Reset() {
	*x = BonusOpActivityInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_cmd_op_activity_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BonusOpActivityInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BonusOpActivityInfo) ProtoMessage() {}

func (x *BonusOpActivityInfo) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_cmd_op_activity_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BonusOpActivityInfo.ProtoReflect.Descriptor instead.
func (*BonusOpActivityInfo) Descriptor() ([]byte, []int) {
	return file_cmd_cmd_op_activity_proto_rawDescGZIP(), []int{1}
}

func (x *BonusOpActivityInfo) GetLeftBonusCount() uint32 {
	if x != nil {
		return x.LeftBonusCount
	}
	return 0
}

type GetOpActivityInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetOpActivityInfoReq) Reset() {
	*x = GetOpActivityInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_cmd_op_activity_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOpActivityInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOpActivityInfoReq) ProtoMessage() {}

func (x *GetOpActivityInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_cmd_op_activity_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOpActivityInfoReq.ProtoReflect.Descriptor instead.
func (*GetOpActivityInfoReq) Descriptor() ([]byte, []int) {
	return file_cmd_cmd_op_activity_proto_rawDescGZIP(), []int{2}
}

type GetOpActivityInfoRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Retcode            int32             `protobuf:"varint,10,opt,name=retcode,proto3" json:"retcode,omitempty"`
	OpActivityInfoList []*OpActivityInfo `protobuf:"bytes,7,rep,name=op_activity_info_list,json=opActivityInfoList,proto3" json:"op_activity_info_list,omitempty"`
}

func (x *GetOpActivityInfoRsp) Reset() {
	*x = GetOpActivityInfoRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_cmd_op_activity_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOpActivityInfoRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOpActivityInfoRsp) ProtoMessage() {}

func (x *GetOpActivityInfoRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_cmd_op_activity_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOpActivityInfoRsp.ProtoReflect.Descriptor instead.
func (*GetOpActivityInfoRsp) Descriptor() ([]byte, []int) {
	return file_cmd_cmd_op_activity_proto_rawDescGZIP(), []int{3}
}

func (x *GetOpActivityInfoRsp) GetRetcode() int32 {
	if x != nil {
		return x.Retcode
	}
	return 0
}

func (x *GetOpActivityInfoRsp) GetOpActivityInfoList() []*OpActivityInfo {
	if x != nil {
		return x.OpActivityInfoList
	}
	return nil
}

type OpActivityDataNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OpActivityInfoList []*OpActivityInfo `protobuf:"bytes,15,rep,name=op_activity_info_list,json=opActivityInfoList,proto3" json:"op_activity_info_list,omitempty"`
}

func (x *OpActivityDataNotify) Reset() {
	*x = OpActivityDataNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_cmd_op_activity_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpActivityDataNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpActivityDataNotify) ProtoMessage() {}

func (x *OpActivityDataNotify) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_cmd_op_activity_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpActivityDataNotify.ProtoReflect.Descriptor instead.
func (*OpActivityDataNotify) Descriptor() ([]byte, []int) {
	return file_cmd_cmd_op_activity_proto_rawDescGZIP(), []int{4}
}

func (x *OpActivityDataNotify) GetOpActivityInfoList() []*OpActivityInfo {
	if x != nil {
		return x.OpActivityInfoList
	}
	return nil
}

type OpActivityUpdateNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OpActivityInfo *OpActivityInfo `protobuf:"bytes,6,opt,name=op_activity_info,json=opActivityInfo,proto3" json:"op_activity_info,omitempty"`
}

func (x *OpActivityUpdateNotify) Reset() {
	*x = OpActivityUpdateNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_cmd_op_activity_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpActivityUpdateNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpActivityUpdateNotify) ProtoMessage() {}

func (x *OpActivityUpdateNotify) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_cmd_op_activity_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpActivityUpdateNotify.ProtoReflect.Descriptor instead.
func (*OpActivityUpdateNotify) Descriptor() ([]byte, []int) {
	return file_cmd_cmd_op_activity_proto_rawDescGZIP(), []int{5}
}

func (x *OpActivityUpdateNotify) GetOpActivityInfo() *OpActivityInfo {
	if x != nil {
		return x.OpActivityInfo
	}
	return nil
}

var File_cmd_cmd_op_activity_proto protoreflect.FileDescriptor

var file_cmd_cmd_op_activity_proto_rawDesc = []byte{
	0x0a, 0x19, 0x63, 0x6d, 0x64, 0x2f, 0x63, 0x6d, 0x64, 0x5f, 0x6f, 0x70, 0x5f, 0x61, 0x63, 0x74,
	0x69, 0x76, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xf7, 0x01, 0x0a, 0x0e, 0x4f, 0x70, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74,
	0x79, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74,
	0x79, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x61, 0x63, 0x74, 0x69,
	0x76, 0x69, 0x74, 0x79, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d,
	0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x65, 0x67, 0x69, 0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x62, 0x65, 0x67, 0x69, 0x6e, 0x54, 0x69, 0x6d, 0x65,
	0x12, 0x22, 0x0a, 0x0d, 0x69, 0x73, 0x5f, 0x68, 0x61, 0x73, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x69, 0x73, 0x48, 0x61, 0x73, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x73, 0x63, 0x68, 0x65, 0x64,
	0x75, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x3b, 0x0a, 0x0a, 0x62, 0x6f, 0x6e, 0x75, 0x73, 0x5f, 0x69,
	0x6e, 0x66, 0x6f, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x42, 0x6f, 0x6e, 0x75, 0x73, 0x4f, 0x70, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74,
	0x79, 0x49, 0x6e, 0x66, 0x6f, 0x48, 0x00, 0x52, 0x09, 0x62, 0x6f, 0x6e, 0x75, 0x73, 0x49, 0x6e,
	0x66, 0x6f, 0x42, 0x08, 0x0a, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x22, 0x3f, 0x0a, 0x13,
	0x42, 0x6f, 0x6e, 0x75, 0x73, 0x4f, 0x70, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x28, 0x0a, 0x10, 0x6c, 0x65, 0x66, 0x74, 0x5f, 0x62, 0x6f, 0x6e, 0x75,
	0x73, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0e, 0x6c,
	0x65, 0x66, 0x74, 0x42, 0x6f, 0x6e, 0x75, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x16, 0x0a,
	0x14, 0x47, 0x65, 0x74, 0x4f, 0x70, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x65, 0x71, 0x22, 0x7a, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x4f, 0x70, 0x41, 0x63,
	0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x73, 0x70, 0x12, 0x18, 0x0a,
	0x07, 0x72, 0x65, 0x74, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07,
	0x72, 0x65, 0x74, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x48, 0x0a, 0x15, 0x6f, 0x70, 0x5f, 0x61, 0x63,
	0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x5f, 0x6c, 0x69, 0x73, 0x74,
	0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4f,
	0x70, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x12, 0x6f,
	0x70, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x4c, 0x69, 0x73,
	0x74, 0x22, 0x60, 0x0a, 0x14, 0x4f, 0x70, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x44,
	0x61, 0x74, 0x61, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x48, 0x0a, 0x15, 0x6f, 0x70, 0x5f,
	0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x5f, 0x6c, 0x69,
	0x73, 0x74, 0x18, 0x0f, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x4f, 0x70, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x12, 0x6f, 0x70, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x4c,
	0x69, 0x73, 0x74, 0x22, 0x59, 0x0a, 0x16, 0x4f, 0x70, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74,
	0x79, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x3f, 0x0a,
	0x10, 0x6f, 0x70, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x5f, 0x69, 0x6e, 0x66,
	0x6f, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x4f, 0x70, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0e,
	0x6f, 0x70, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x28,
	0x5a, 0x26, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x65, 0x79,
	0x76, 0x61, 0x74, 0x2d, 0x68, 0x65, 0x6c, 0x70, 0x65, 0x72, 0x2f, 0x68, 0x6b, 0x34, 0x65, 0x2d,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cmd_cmd_op_activity_proto_rawDescOnce sync.Once
	file_cmd_cmd_op_activity_proto_rawDescData = file_cmd_cmd_op_activity_proto_rawDesc
)

func file_cmd_cmd_op_activity_proto_rawDescGZIP() []byte {
	file_cmd_cmd_op_activity_proto_rawDescOnce.Do(func() {
		file_cmd_cmd_op_activity_proto_rawDescData = protoimpl.X.CompressGZIP(file_cmd_cmd_op_activity_proto_rawDescData)
	})
	return file_cmd_cmd_op_activity_proto_rawDescData
}

var file_cmd_cmd_op_activity_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_cmd_cmd_op_activity_proto_goTypes = []interface{}{
	(*OpActivityInfo)(nil),         // 0: proto.OpActivityInfo
	(*BonusOpActivityInfo)(nil),    // 1: proto.BonusOpActivityInfo
	(*GetOpActivityInfoReq)(nil),   // 2: proto.GetOpActivityInfoReq
	(*GetOpActivityInfoRsp)(nil),   // 3: proto.GetOpActivityInfoRsp
	(*OpActivityDataNotify)(nil),   // 4: proto.OpActivityDataNotify
	(*OpActivityUpdateNotify)(nil), // 5: proto.OpActivityUpdateNotify
}
var file_cmd_cmd_op_activity_proto_depIdxs = []int32{
	1, // 0: proto.OpActivityInfo.bonus_info:type_name -> proto.BonusOpActivityInfo
	0, // 1: proto.GetOpActivityInfoRsp.op_activity_info_list:type_name -> proto.OpActivityInfo
	0, // 2: proto.OpActivityDataNotify.op_activity_info_list:type_name -> proto.OpActivityInfo
	0, // 3: proto.OpActivityUpdateNotify.op_activity_info:type_name -> proto.OpActivityInfo
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_cmd_cmd_op_activity_proto_init() }
func file_cmd_cmd_op_activity_proto_init() {
	if File_cmd_cmd_op_activity_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cmd_cmd_op_activity_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpActivityInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_cmd_op_activity_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BonusOpActivityInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_cmd_op_activity_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOpActivityInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_cmd_op_activity_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOpActivityInfoRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_cmd_op_activity_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpActivityDataNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_cmd_op_activity_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpActivityUpdateNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_cmd_cmd_op_activity_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*OpActivityInfo_BonusInfo)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cmd_cmd_op_activity_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cmd_cmd_op_activity_proto_goTypes,
		DependencyIndexes: file_cmd_cmd_op_activity_proto_depIdxs,
		MessageInfos:      file_cmd_cmd_op_activity_proto_msgTypes,
	}.Build()
	File_cmd_cmd_op_activity_proto = out.File
	file_cmd_cmd_op_activity_proto_rawDesc = nil
	file_cmd_cmd_op_activity_proto_goTypes = nil
	file_cmd_cmd_op_activity_proto_depIdxs = nil
}
