// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.7
// source: server_only/cmd_offline_op.server.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OfflineOpDefaultContext struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tag uint32 `protobuf:"varint,1,opt,name=tag,proto3" json:"tag,omitempty"`
}

func (x *OfflineOpDefaultContext) Reset() {
	*x = OfflineOpDefaultContext{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_only_cmd_offline_op_server_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OfflineOpDefaultContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfflineOpDefaultContext) ProtoMessage() {}

func (x *OfflineOpDefaultContext) ProtoReflect() protoreflect.Message {
	mi := &file_server_only_cmd_offline_op_server_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfflineOpDefaultContext.ProtoReflect.Descriptor instead.
func (*OfflineOpDefaultContext) Descriptor() ([]byte, []int) {
	return file_server_only_cmd_offline_op_server_proto_rawDescGZIP(), []int{0}
}

func (x *OfflineOpDefaultContext) GetTag() uint32 {
	if x != nil {
		return x.Tag
	}
	return 0
}

type OfflineOpPlantFlowerActivityGiveFlowerContext struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid          uint32            `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	FlowerNumMap map[uint32]uint32 `protobuf:"bytes,2,rep,name=flower_num_map,json=flowerNumMap,proto3" json:"flower_num_map,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (x *OfflineOpPlantFlowerActivityGiveFlowerContext) Reset() {
	*x = OfflineOpPlantFlowerActivityGiveFlowerContext{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_only_cmd_offline_op_server_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OfflineOpPlantFlowerActivityGiveFlowerContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfflineOpPlantFlowerActivityGiveFlowerContext) ProtoMessage() {}

func (x *OfflineOpPlantFlowerActivityGiveFlowerContext) ProtoReflect() protoreflect.Message {
	mi := &file_server_only_cmd_offline_op_server_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfflineOpPlantFlowerActivityGiveFlowerContext.ProtoReflect.Descriptor instead.
func (*OfflineOpPlantFlowerActivityGiveFlowerContext) Descriptor() ([]byte, []int) {
	return file_server_only_cmd_offline_op_server_proto_rawDescGZIP(), []int{1}
}

func (x *OfflineOpPlantFlowerActivityGiveFlowerContext) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *OfflineOpPlantFlowerActivityGiveFlowerContext) GetFlowerNumMap() map[uint32]uint32 {
	if x != nil {
		return x.FlowerNumMap
	}
	return nil
}

type GCGSettleContext struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid     uint32 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	GameId  uint32 `protobuf:"varint,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	GameUid uint32 `protobuf:"varint,3,opt,name=game_uid,json=gameUid,proto3" json:"game_uid,omitempty"`
}

func (x *GCGSettleContext) Reset() {
	*x = GCGSettleContext{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_only_cmd_offline_op_server_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GCGSettleContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GCGSettleContext) ProtoMessage() {}

func (x *GCGSettleContext) ProtoReflect() protoreflect.Message {
	mi := &file_server_only_cmd_offline_op_server_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GCGSettleContext.ProtoReflect.Descriptor instead.
func (*GCGSettleContext) Descriptor() ([]byte, []int) {
	return file_server_only_cmd_offline_op_server_proto_rawDescGZIP(), []int{2}
}

func (x *GCGSettleContext) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *GCGSettleContext) GetGameId() uint32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *GCGSettleContext) GetGameUid() uint32 {
	if x != nil {
		return x.GameUid
	}
	return 0
}

type OfflineOpContext struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Context:
	//
	//	*OfflineOpContext_DefaultContext
	//	*OfflineOpContext_PlantFlowerGiveFlowerContext
	Context isOfflineOpContext_Context `protobuf_oneof:"context"`
}

func (x *OfflineOpContext) Reset() {
	*x = OfflineOpContext{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_only_cmd_offline_op_server_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OfflineOpContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfflineOpContext) ProtoMessage() {}

func (x *OfflineOpContext) ProtoReflect() protoreflect.Message {
	mi := &file_server_only_cmd_offline_op_server_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfflineOpContext.ProtoReflect.Descriptor instead.
func (*OfflineOpContext) Descriptor() ([]byte, []int) {
	return file_server_only_cmd_offline_op_server_proto_rawDescGZIP(), []int{3}
}

func (m *OfflineOpContext) GetContext() isOfflineOpContext_Context {
	if m != nil {
		return m.Context
	}
	return nil
}

func (x *OfflineOpContext) GetDefaultContext() *OfflineOpDefaultContext {
	if x, ok := x.GetContext().(*OfflineOpContext_DefaultContext); ok {
		return x.DefaultContext
	}
	return nil
}

func (x *OfflineOpContext) GetPlantFlowerGiveFlowerContext() *OfflineOpPlantFlowerActivityGiveFlowerContext {
	if x, ok := x.GetContext().(*OfflineOpContext_PlantFlowerGiveFlowerContext); ok {
		return x.PlantFlowerGiveFlowerContext
	}
	return nil
}

type isOfflineOpContext_Context interface {
	isOfflineOpContext_Context()
}

type OfflineOpContext_DefaultContext struct {
	DefaultContext *OfflineOpDefaultContext `protobuf:"bytes,1,opt,name=default_context,json=defaultContext,proto3,oneof"`
}

type OfflineOpContext_PlantFlowerGiveFlowerContext struct {
	PlantFlowerGiveFlowerContext *OfflineOpPlantFlowerActivityGiveFlowerContext `protobuf:"bytes,2,opt,name=plant_flower_give_flower_context,json=plantFlowerGiveFlowerContext,proto3,oneof"`
}

func (*OfflineOpContext_DefaultContext) isOfflineOpContext_Context() {}

func (*OfflineOpContext_PlantFlowerGiveFlowerContext) isOfflineOpContext_Context() {}

type OfflineOpData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bin       *OfflineOpBin     `protobuf:"bytes,1,opt,name=bin,proto3" json:"bin,omitempty"`
	Context   *OfflineOpContext `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	MaxLength uint32            `protobuf:"varint,3,opt,name=max_length,json=maxLength,proto3" json:"max_length,omitempty"`
}

func (x *OfflineOpData) Reset() {
	*x = OfflineOpData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_only_cmd_offline_op_server_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OfflineOpData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfflineOpData) ProtoMessage() {}

func (x *OfflineOpData) ProtoReflect() protoreflect.Message {
	mi := &file_server_only_cmd_offline_op_server_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfflineOpData.ProtoReflect.Descriptor instead.
func (*OfflineOpData) Descriptor() ([]byte, []int) {
	return file_server_only_cmd_offline_op_server_proto_rawDescGZIP(), []int{4}
}

func (x *OfflineOpData) GetBin() *OfflineOpBin {
	if x != nil {
		return x.Bin
	}
	return nil
}

func (x *OfflineOpData) GetContext() *OfflineOpContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *OfflineOpData) GetMaxLength() uint32 {
	if x != nil {
		return x.MaxLength
	}
	return 0
}

type SendOfflineOpReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid    uint32         `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Time   uint32         `protobuf:"fixed32,2,opt,name=time,proto3" json:"time,omitempty"`
	OpType OfflineOpType  `protobuf:"varint,3,opt,name=op_type,json=opType,proto3,enum=proto.OfflineOpType" json:"op_type,omitempty"`
	OpData *OfflineOpData `protobuf:"bytes,4,opt,name=op_data,json=opData,proto3" json:"op_data,omitempty"`
}

func (x *SendOfflineOpReq) Reset() {
	*x = SendOfflineOpReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_only_cmd_offline_op_server_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendOfflineOpReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendOfflineOpReq) ProtoMessage() {}

func (x *SendOfflineOpReq) ProtoReflect() protoreflect.Message {
	mi := &file_server_only_cmd_offline_op_server_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendOfflineOpReq.ProtoReflect.Descriptor instead.
func (*SendOfflineOpReq) Descriptor() ([]byte, []int) {
	return file_server_only_cmd_offline_op_server_proto_rawDescGZIP(), []int{5}
}

func (x *SendOfflineOpReq) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *SendOfflineOpReq) GetTime() uint32 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *SendOfflineOpReq) GetOpType() OfflineOpType {
	if x != nil {
		return x.OpType
	}
	return OfflineOpType_OFFLINE_OP_NONE
}

func (x *SendOfflineOpReq) GetOpData() *OfflineOpData {
	if x != nil {
		return x.OpData
	}
	return nil
}

type SendOfflineOpRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Retcode int32             `protobuf:"varint,1,opt,name=retcode,proto3" json:"retcode,omitempty"`
	Index   uint32            `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	OpType  OfflineOpType     `protobuf:"varint,3,opt,name=op_type,json=opType,proto3,enum=proto.OfflineOpType" json:"op_type,omitempty"`
	Context *OfflineOpContext `protobuf:"bytes,4,opt,name=context,proto3" json:"context,omitempty"`
}

func (x *SendOfflineOpRsp) Reset() {
	*x = SendOfflineOpRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_only_cmd_offline_op_server_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendOfflineOpRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendOfflineOpRsp) ProtoMessage() {}

func (x *SendOfflineOpRsp) ProtoReflect() protoreflect.Message {
	mi := &file_server_only_cmd_offline_op_server_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendOfflineOpRsp.ProtoReflect.Descriptor instead.
func (*SendOfflineOpRsp) Descriptor() ([]byte, []int) {
	return file_server_only_cmd_offline_op_server_proto_rawDescGZIP(), []int{6}
}

func (x *SendOfflineOpRsp) GetRetcode() int32 {
	if x != nil {
		return x.Retcode
	}
	return 0
}

func (x *SendOfflineOpRsp) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *SendOfflineOpRsp) GetOpType() OfflineOpType {
	if x != nil {
		return x.OpType
	}
	return OfflineOpType_OFFLINE_OP_NONE
}

func (x *SendOfflineOpRsp) GetContext() *OfflineOpContext {
	if x != nil {
		return x.Context
	}
	return nil
}

type GetOfflineOpReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OpType OfflineOpType `protobuf:"varint,1,opt,name=op_type,json=opType,proto3,enum=proto.OfflineOpType" json:"op_type,omitempty"`
	Index  uint32        `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
}

func (x *GetOfflineOpReq) Reset() {
	*x = GetOfflineOpReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_only_cmd_offline_op_server_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOfflineOpReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOfflineOpReq) ProtoMessage() {}

func (x *GetOfflineOpReq) ProtoReflect() protoreflect.Message {
	mi := &file_server_only_cmd_offline_op_server_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOfflineOpReq.ProtoReflect.Descriptor instead.
func (*GetOfflineOpReq) Descriptor() ([]byte, []int) {
	return file_server_only_cmd_offline_op_server_proto_rawDescGZIP(), []int{7}
}

func (x *GetOfflineOpReq) GetOpType() OfflineOpType {
	if x != nil {
		return x.OpType
	}
	return OfflineOpType_OFFLINE_OP_NONE
}

func (x *GetOfflineOpReq) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

type GetOfflineOpRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Retcode    int32    `protobuf:"varint,1,opt,name=retcode,proto3" json:"retcode,omitempty"`
	BinStrList [][]byte `protobuf:"bytes,2,rep,name=bin_str_list,json=binStrList,proto3" json:"bin_str_list,omitempty"`
}

func (x *GetOfflineOpRsp) Reset() {
	*x = GetOfflineOpRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_only_cmd_offline_op_server_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOfflineOpRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOfflineOpRsp) ProtoMessage() {}

func (x *GetOfflineOpRsp) ProtoReflect() protoreflect.Message {
	mi := &file_server_only_cmd_offline_op_server_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOfflineOpRsp.ProtoReflect.Descriptor instead.
func (*GetOfflineOpRsp) Descriptor() ([]byte, []int) {
	return file_server_only_cmd_offline_op_server_proto_rawDescGZIP(), []int{8}
}

func (x *GetOfflineOpRsp) GetRetcode() int32 {
	if x != nil {
		return x.Retcode
	}
	return 0
}

func (x *GetOfflineOpRsp) GetBinStrList() [][]byte {
	if x != nil {
		return x.BinStrList
	}
	return nil
}

type NewOfflineOpNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OpType OfflineOpType `protobuf:"varint,1,opt,name=op_type,json=opType,proto3,enum=proto.OfflineOpType" json:"op_type,omitempty"`
	Index  uint32        `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
}

func (x *NewOfflineOpNotify) Reset() {
	*x = NewOfflineOpNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_only_cmd_offline_op_server_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewOfflineOpNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewOfflineOpNotify) ProtoMessage() {}

func (x *NewOfflineOpNotify) ProtoReflect() protoreflect.Message {
	mi := &file_server_only_cmd_offline_op_server_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewOfflineOpNotify.ProtoReflect.Descriptor instead.
func (*NewOfflineOpNotify) Descriptor() ([]byte, []int) {
	return file_server_only_cmd_offline_op_server_proto_rawDescGZIP(), []int{9}
}

func (x *NewOfflineOpNotify) GetOpType() OfflineOpType {
	if x != nil {
		return x.OpType
	}
	return OfflineOpType_OFFLINE_OP_NONE
}

func (x *NewOfflineOpNotify) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

type RemoveOfflineOpReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OpType OfflineOpType `protobuf:"varint,1,opt,name=op_type,json=opType,proto3,enum=proto.OfflineOpType" json:"op_type,omitempty"`
	Index  uint32        `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
}

func (x *RemoveOfflineOpReq) Reset() {
	*x = RemoveOfflineOpReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_only_cmd_offline_op_server_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveOfflineOpReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveOfflineOpReq) ProtoMessage() {}

func (x *RemoveOfflineOpReq) ProtoReflect() protoreflect.Message {
	mi := &file_server_only_cmd_offline_op_server_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveOfflineOpReq.ProtoReflect.Descriptor instead.
func (*RemoveOfflineOpReq) Descriptor() ([]byte, []int) {
	return file_server_only_cmd_offline_op_server_proto_rawDescGZIP(), []int{10}
}

func (x *RemoveOfflineOpReq) GetOpType() OfflineOpType {
	if x != nil {
		return x.OpType
	}
	return OfflineOpType_OFFLINE_OP_NONE
}

func (x *RemoveOfflineOpReq) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

type RemoveOfflineOpRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Retcode int32         `protobuf:"varint,1,opt,name=retcode,proto3" json:"retcode,omitempty"`
	OpType  OfflineOpType `protobuf:"varint,2,opt,name=op_type,json=opType,proto3,enum=proto.OfflineOpType" json:"op_type,omitempty"`
	Index   uint32        `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
}

func (x *RemoveOfflineOpRsp) Reset() {
	*x = RemoveOfflineOpRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_only_cmd_offline_op_server_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveOfflineOpRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveOfflineOpRsp) ProtoMessage() {}

func (x *RemoveOfflineOpRsp) ProtoReflect() protoreflect.Message {
	mi := &file_server_only_cmd_offline_op_server_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveOfflineOpRsp.ProtoReflect.Descriptor instead.
func (*RemoveOfflineOpRsp) Descriptor() ([]byte, []int) {
	return file_server_only_cmd_offline_op_server_proto_rawDescGZIP(), []int{11}
}

func (x *RemoveOfflineOpRsp) GetRetcode() int32 {
	if x != nil {
		return x.Retcode
	}
	return 0
}

func (x *RemoveOfflineOpRsp) GetOpType() OfflineOpType {
	if x != nil {
		return x.OpType
	}
	return OfflineOpType_OFFLINE_OP_NONE
}

func (x *RemoveOfflineOpRsp) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

type SendGCGOfflineOpReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid    uint32         `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Time   uint32         `protobuf:"fixed32,2,opt,name=time,proto3" json:"time,omitempty"`
	OpType OfflineOpType  `protobuf:"varint,3,opt,name=op_type,json=opType,proto3,enum=proto.OfflineOpType" json:"op_type,omitempty"`
	OpData *OfflineOpData `protobuf:"bytes,4,opt,name=op_data,json=opData,proto3" json:"op_data,omitempty"`
}

func (x *SendGCGOfflineOpReq) Reset() {
	*x = SendGCGOfflineOpReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_only_cmd_offline_op_server_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendGCGOfflineOpReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendGCGOfflineOpReq) ProtoMessage() {}

func (x *SendGCGOfflineOpReq) ProtoReflect() protoreflect.Message {
	mi := &file_server_only_cmd_offline_op_server_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendGCGOfflineOpReq.ProtoReflect.Descriptor instead.
func (*SendGCGOfflineOpReq) Descriptor() ([]byte, []int) {
	return file_server_only_cmd_offline_op_server_proto_rawDescGZIP(), []int{12}
}

func (x *SendGCGOfflineOpReq) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *SendGCGOfflineOpReq) GetTime() uint32 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *SendGCGOfflineOpReq) GetOpType() OfflineOpType {
	if x != nil {
		return x.OpType
	}
	return OfflineOpType_OFFLINE_OP_NONE
}

func (x *SendGCGOfflineOpReq) GetOpData() *OfflineOpData {
	if x != nil {
		return x.OpData
	}
	return nil
}

type SendGCGOfflineOpRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Retcode int32             `protobuf:"varint,1,opt,name=retcode,proto3" json:"retcode,omitempty"`
	Index   uint32            `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	OpType  OfflineOpType     `protobuf:"varint,3,opt,name=op_type,json=opType,proto3,enum=proto.OfflineOpType" json:"op_type,omitempty"`
	Context *OfflineOpContext `protobuf:"bytes,4,opt,name=context,proto3" json:"context,omitempty"`
}

func (x *SendGCGOfflineOpRsp) Reset() {
	*x = SendGCGOfflineOpRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_only_cmd_offline_op_server_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendGCGOfflineOpRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendGCGOfflineOpRsp) ProtoMessage() {}

func (x *SendGCGOfflineOpRsp) ProtoReflect() protoreflect.Message {
	mi := &file_server_only_cmd_offline_op_server_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendGCGOfflineOpRsp.ProtoReflect.Descriptor instead.
func (*SendGCGOfflineOpRsp) Descriptor() ([]byte, []int) {
	return file_server_only_cmd_offline_op_server_proto_rawDescGZIP(), []int{13}
}

func (x *SendGCGOfflineOpRsp) GetRetcode() int32 {
	if x != nil {
		return x.Retcode
	}
	return 0
}

func (x *SendGCGOfflineOpRsp) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *SendGCGOfflineOpRsp) GetOpType() OfflineOpType {
	if x != nil {
		return x.OpType
	}
	return OfflineOpType_OFFLINE_OP_NONE
}

func (x *SendGCGOfflineOpRsp) GetContext() *OfflineOpContext {
	if x != nil {
		return x.Context
	}
	return nil
}

var File_server_only_cmd_offline_op_server_proto protoreflect.FileDescriptor

var file_server_only_cmd_offline_op_server_proto_rawDesc = []byte{
	0x0a, 0x27, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x6f, 0x6e, 0x6c, 0x79, 0x2f, 0x63, 0x6d,
	0x64, 0x5f, 0x6f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x6f, 0x70, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x23, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x6f, 0x6e, 0x6c, 0x79, 0x2f, 0x62, 0x69,
	0x6e, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2b, 0x0a, 0x17, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65,
	0x4f, 0x70, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x74,
	0x61, 0x67, 0x22, 0xf0, 0x01, 0x0a, 0x2d, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x4f, 0x70,
	0x50, 0x6c, 0x61, 0x6e, 0x74, 0x46, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x41, 0x63, 0x74, 0x69, 0x76,
	0x69, 0x74, 0x79, 0x47, 0x69, 0x76, 0x65, 0x46, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x43, 0x6f, 0x6e,
	0x74, 0x65, 0x78, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x6c, 0x0a, 0x0e, 0x66, 0x6c, 0x6f, 0x77, 0x65, 0x72,
	0x5f, 0x6e, 0x75, 0x6d, 0x5f, 0x6d, 0x61, 0x70, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x46,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x4f, 0x70,
	0x50, 0x6c, 0x61, 0x6e, 0x74, 0x46, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x41, 0x63, 0x74, 0x69, 0x76,
	0x69, 0x74, 0x79, 0x47, 0x69, 0x76, 0x65, 0x46, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x43, 0x6f, 0x6e,
	0x74, 0x65, 0x78, 0x74, 0x2e, 0x46, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x4d, 0x61,
	0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0c, 0x66, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x4e, 0x75,
	0x6d, 0x4d, 0x61, 0x70, 0x1a, 0x3f, 0x0a, 0x11, 0x46, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x4e, 0x75,
	0x6d, 0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x58, 0x0a, 0x10, 0x47, 0x43, 0x47, 0x53, 0x65, 0x74, 0x74,
	0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x67,
	0x61, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x67, 0x61,
	0x6d, 0x65, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x75, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x67, 0x61, 0x6d, 0x65, 0x55, 0x69, 0x64, 0x22,
	0xe8, 0x01, 0x0a, 0x10, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x4f, 0x70, 0x43, 0x6f, 0x6e,
	0x74, 0x65, 0x78, 0x74, 0x12, 0x49, 0x0a, 0x0f, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x5f,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x4f, 0x70, 0x44,
	0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x48, 0x00, 0x52,
	0x0e, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x12,
	0x7e, 0x0a, 0x20, 0x70, 0x6c, 0x61, 0x6e, 0x74, 0x5f, 0x66, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x5f,
	0x67, 0x69, 0x76, 0x65, 0x5f, 0x66, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x34, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x4f, 0x70, 0x50, 0x6c, 0x61, 0x6e, 0x74,
	0x46, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x47, 0x69,
	0x76, 0x65, 0x46, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x48,
	0x00, 0x52, 0x1c, 0x70, 0x6c, 0x61, 0x6e, 0x74, 0x46, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x47, 0x69,
	0x76, 0x65, 0x46, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x42,
	0x09, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x22, 0x88, 0x01, 0x0a, 0x0d, 0x4f,
	0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x4f, 0x70, 0x44, 0x61, 0x74, 0x61, 0x12, 0x25, 0x0a, 0x03,
	0x62, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x4f, 0x70, 0x42, 0x69, 0x6e, 0x52, 0x03,
	0x62, 0x69, 0x6e, 0x12, 0x31, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4f, 0x66, 0x66,
	0x6c, 0x69, 0x6e, 0x65, 0x4f, 0x70, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x52, 0x07, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x61, 0x78, 0x5f, 0x6c, 0x65,
	0x6e, 0x67, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x6d, 0x61, 0x78, 0x4c,
	0x65, 0x6e, 0x67, 0x74, 0x68, 0x22, 0x96, 0x01, 0x0a, 0x10, 0x53, 0x65, 0x6e, 0x64, 0x4f, 0x66,
	0x66, 0x6c, 0x69, 0x6e, 0x65, 0x4f, 0x70, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x07, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65,
	0x12, 0x2d, 0x0a, 0x07, 0x6f, 0x70, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e,
	0x65, 0x4f, 0x70, 0x54, 0x79, 0x70, 0x65, 0x52, 0x06, 0x6f, 0x70, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x2d, 0x0a, 0x07, 0x6f, 0x70, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65,
	0x4f, 0x70, 0x44, 0x61, 0x74, 0x61, 0x52, 0x06, 0x6f, 0x70, 0x44, 0x61, 0x74, 0x61, 0x22, 0xa4,
	0x01, 0x0a, 0x10, 0x53, 0x65, 0x6e, 0x64, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x4f, 0x70,
	0x52, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x74, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x72, 0x65, 0x74, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x69, 0x6e,
	0x64, 0x65, 0x78, 0x12, 0x2d, 0x0a, 0x07, 0x6f, 0x70, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4f, 0x66, 0x66,
	0x6c, 0x69, 0x6e, 0x65, 0x4f, 0x70, 0x54, 0x79, 0x70, 0x65, 0x52, 0x06, 0x6f, 0x70, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x31, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4f, 0x66, 0x66, 0x6c,
	0x69, 0x6e, 0x65, 0x4f, 0x70, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x52, 0x07, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x78, 0x74, 0x22, 0x56, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x4f, 0x66, 0x66, 0x6c,
	0x69, 0x6e, 0x65, 0x4f, 0x70, 0x52, 0x65, 0x71, 0x12, 0x2d, 0x0a, 0x07, 0x6f, 0x70, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x4f, 0x70, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x06, 0x6f, 0x70, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x4d, 0x0a,
	0x0f, 0x47, 0x65, 0x74, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x4f, 0x70, 0x52, 0x73, 0x70,
	0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x74, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x07, 0x72, 0x65, 0x74, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x20, 0x0a, 0x0c, 0x62, 0x69,
	0x6e, 0x5f, 0x73, 0x74, 0x72, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0c,
	0x52, 0x0a, 0x62, 0x69, 0x6e, 0x53, 0x74, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x59, 0x0a, 0x12,
	0x4e, 0x65, 0x77, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x4f, 0x70, 0x4e, 0x6f, 0x74, 0x69,
	0x66, 0x79, 0x12, 0x2d, 0x0a, 0x07, 0x6f, 0x70, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4f, 0x66, 0x66, 0x6c,
	0x69, 0x6e, 0x65, 0x4f, 0x70, 0x54, 0x79, 0x70, 0x65, 0x52, 0x06, 0x6f, 0x70, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x59, 0x0a, 0x12, 0x52, 0x65, 0x6d, 0x6f, 0x76,
	0x65, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x4f, 0x70, 0x52, 0x65, 0x71, 0x12, 0x2d, 0x0a,
	0x07, 0x6f, 0x70, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x4f, 0x70,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x06, 0x6f, 0x70, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x69, 0x6e, 0x64,
	0x65, 0x78, 0x22, 0x73, 0x0a, 0x12, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x4f, 0x66, 0x66, 0x6c,
	0x69, 0x6e, 0x65, 0x4f, 0x70, 0x52, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x74, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x72, 0x65, 0x74, 0x63, 0x6f,
	0x64, 0x65, 0x12, 0x2d, 0x0a, 0x07, 0x6f, 0x70, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4f, 0x66, 0x66, 0x6c,
	0x69, 0x6e, 0x65, 0x4f, 0x70, 0x54, 0x79, 0x70, 0x65, 0x52, 0x06, 0x6f, 0x70, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x99, 0x01, 0x0a, 0x13, 0x53, 0x65, 0x6e, 0x64,
	0x47, 0x43, 0x47, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x4f, 0x70, 0x52, 0x65, 0x71, 0x12,
	0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x75, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x07, 0x52,
	0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x2d, 0x0a, 0x07, 0x6f, 0x70, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4f,
	0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x4f, 0x70, 0x54, 0x79, 0x70, 0x65, 0x52, 0x06, 0x6f, 0x70,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x2d, 0x0a, 0x07, 0x6f, 0x70, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4f, 0x66,
	0x66, 0x6c, 0x69, 0x6e, 0x65, 0x4f, 0x70, 0x44, 0x61, 0x74, 0x61, 0x52, 0x06, 0x6f, 0x70, 0x44,
	0x61, 0x74, 0x61, 0x22, 0xa7, 0x01, 0x0a, 0x13, 0x53, 0x65, 0x6e, 0x64, 0x47, 0x43, 0x47, 0x4f,
	0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x4f, 0x70, 0x52, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x72,
	0x65, 0x74, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x72, 0x65,
	0x74, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x2d, 0x0a, 0x07, 0x6f,
	0x70, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x4f, 0x70, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x06, 0x6f, 0x70, 0x54, 0x79, 0x70, 0x65, 0x12, 0x31, 0x0a, 0x07, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x78, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x4f, 0x70, 0x43, 0x6f, 0x6e,
	0x74, 0x65, 0x78, 0x74, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x42, 0x28, 0x5a,
	0x26, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x65, 0x79, 0x76,
	0x61, 0x74, 0x2d, 0x68, 0x65, 0x6c, 0x70, 0x65, 0x72, 0x2f, 0x68, 0x6b, 0x34, 0x65, 0x2d, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_server_only_cmd_offline_op_server_proto_rawDescOnce sync.Once
	file_server_only_cmd_offline_op_server_proto_rawDescData = file_server_only_cmd_offline_op_server_proto_rawDesc
)

func file_server_only_cmd_offline_op_server_proto_rawDescGZIP() []byte {
	file_server_only_cmd_offline_op_server_proto_rawDescOnce.Do(func() {
		file_server_only_cmd_offline_op_server_proto_rawDescData = protoimpl.X.CompressGZIP(file_server_only_cmd_offline_op_server_proto_rawDescData)
	})
	return file_server_only_cmd_offline_op_server_proto_rawDescData
}

var file_server_only_cmd_offline_op_server_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_server_only_cmd_offline_op_server_proto_goTypes = []interface{}{
	(*OfflineOpDefaultContext)(nil),                       // 0: proto.OfflineOpDefaultContext
	(*OfflineOpPlantFlowerActivityGiveFlowerContext)(nil), // 1: proto.OfflineOpPlantFlowerActivityGiveFlowerContext
	(*GCGSettleContext)(nil),                              // 2: proto.GCGSettleContext
	(*OfflineOpContext)(nil),                              // 3: proto.OfflineOpContext
	(*OfflineOpData)(nil),                                 // 4: proto.OfflineOpData
	(*SendOfflineOpReq)(nil),                              // 5: proto.SendOfflineOpReq
	(*SendOfflineOpRsp)(nil),                              // 6: proto.SendOfflineOpRsp
	(*GetOfflineOpReq)(nil),                               // 7: proto.GetOfflineOpReq
	(*GetOfflineOpRsp)(nil),                               // 8: proto.GetOfflineOpRsp
	(*NewOfflineOpNotify)(nil),                            // 9: proto.NewOfflineOpNotify
	(*RemoveOfflineOpReq)(nil),                            // 10: proto.RemoveOfflineOpReq
	(*RemoveOfflineOpRsp)(nil),                            // 11: proto.RemoveOfflineOpRsp
	(*SendGCGOfflineOpReq)(nil),                           // 12: proto.SendGCGOfflineOpReq
	(*SendGCGOfflineOpRsp)(nil),                           // 13: proto.SendGCGOfflineOpRsp
	nil,                                                   // 14: proto.OfflineOpPlantFlowerActivityGiveFlowerContext.FlowerNumMapEntry
	(*OfflineOpBin)(nil),                                  // 15: proto.OfflineOpBin
	(OfflineOpType)(0),                                    // 16: proto.OfflineOpType
}
var file_server_only_cmd_offline_op_server_proto_depIdxs = []int32{
	14, // 0: proto.OfflineOpPlantFlowerActivityGiveFlowerContext.flower_num_map:type_name -> proto.OfflineOpPlantFlowerActivityGiveFlowerContext.FlowerNumMapEntry
	0,  // 1: proto.OfflineOpContext.default_context:type_name -> proto.OfflineOpDefaultContext
	1,  // 2: proto.OfflineOpContext.plant_flower_give_flower_context:type_name -> proto.OfflineOpPlantFlowerActivityGiveFlowerContext
	15, // 3: proto.OfflineOpData.bin:type_name -> proto.OfflineOpBin
	3,  // 4: proto.OfflineOpData.context:type_name -> proto.OfflineOpContext
	16, // 5: proto.SendOfflineOpReq.op_type:type_name -> proto.OfflineOpType
	4,  // 6: proto.SendOfflineOpReq.op_data:type_name -> proto.OfflineOpData
	16, // 7: proto.SendOfflineOpRsp.op_type:type_name -> proto.OfflineOpType
	3,  // 8: proto.SendOfflineOpRsp.context:type_name -> proto.OfflineOpContext
	16, // 9: proto.GetOfflineOpReq.op_type:type_name -> proto.OfflineOpType
	16, // 10: proto.NewOfflineOpNotify.op_type:type_name -> proto.OfflineOpType
	16, // 11: proto.RemoveOfflineOpReq.op_type:type_name -> proto.OfflineOpType
	16, // 12: proto.RemoveOfflineOpRsp.op_type:type_name -> proto.OfflineOpType
	16, // 13: proto.SendGCGOfflineOpReq.op_type:type_name -> proto.OfflineOpType
	4,  // 14: proto.SendGCGOfflineOpReq.op_data:type_name -> proto.OfflineOpData
	16, // 15: proto.SendGCGOfflineOpRsp.op_type:type_name -> proto.OfflineOpType
	3,  // 16: proto.SendGCGOfflineOpRsp.context:type_name -> proto.OfflineOpContext
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_server_only_cmd_offline_op_server_proto_init() }
func file_server_only_cmd_offline_op_server_proto_init() {
	if File_server_only_cmd_offline_op_server_proto != nil {
		return
	}
	file_server_only_bin_common_server_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_server_only_cmd_offline_op_server_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OfflineOpDefaultContext); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_only_cmd_offline_op_server_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OfflineOpPlantFlowerActivityGiveFlowerContext); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_only_cmd_offline_op_server_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GCGSettleContext); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_only_cmd_offline_op_server_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OfflineOpContext); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_only_cmd_offline_op_server_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OfflineOpData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_only_cmd_offline_op_server_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendOfflineOpReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_only_cmd_offline_op_server_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendOfflineOpRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_only_cmd_offline_op_server_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOfflineOpReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_only_cmd_offline_op_server_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOfflineOpRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_only_cmd_offline_op_server_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewOfflineOpNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_only_cmd_offline_op_server_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveOfflineOpReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_only_cmd_offline_op_server_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveOfflineOpRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_only_cmd_offline_op_server_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendGCGOfflineOpReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_only_cmd_offline_op_server_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendGCGOfflineOpRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_server_only_cmd_offline_op_server_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*OfflineOpContext_DefaultContext)(nil),
		(*OfflineOpContext_PlantFlowerGiveFlowerContext)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_server_only_cmd_offline_op_server_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_server_only_cmd_offline_op_server_proto_goTypes,
		DependencyIndexes: file_server_only_cmd_offline_op_server_proto_depIdxs,
		MessageInfos:      file_server_only_cmd_offline_op_server_proto_msgTypes,
	}.Build()
	File_server_only_cmd_offline_op_server_proto = out.File
	file_server_only_cmd_offline_op_server_proto_rawDesc = nil
	file_server_only_cmd_offline_op_server_proto_goTypes = nil
	file_server_only_cmd_offline_op_server_proto_depIdxs = nil
}
