// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.7
// source: cmd/cmd_recharge.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RechargeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayProduct    *PlayProduct        `protobuf:"bytes,10,opt,name=play_product,json=playProduct,proto3" json:"play_product,omitempty"`
	CardProduct    *ShopCardProduct    `protobuf:"bytes,8,opt,name=card_product,json=cardProduct,proto3" json:"card_product,omitempty"`
	McoinProduct   *ShopMcoinProduct   `protobuf:"bytes,14,opt,name=mcoin_product,json=mcoinProduct,proto3" json:"mcoin_product,omitempty"`
	ConcertProduct *ShopConcertProduct `protobuf:"bytes,7,opt,name=concert_product,json=concertProduct,proto3" json:"concert_product,omitempty"`
}

func (x *RechargeReq) Reset() {
	*x = RechargeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_cmd_recharge_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RechargeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RechargeReq) ProtoMessage() {}

func (x *RechargeReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_cmd_recharge_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RechargeReq.ProtoReflect.Descriptor instead.
func (*RechargeReq) Descriptor() ([]byte, []int) {
	return file_cmd_cmd_recharge_proto_rawDescGZIP(), []int{0}
}

func (x *RechargeReq) GetPlayProduct() *PlayProduct {
	if x != nil {
		return x.PlayProduct
	}
	return nil
}

func (x *RechargeReq) GetCardProduct() *ShopCardProduct {
	if x != nil {
		return x.CardProduct
	}
	return nil
}

func (x *RechargeReq) GetMcoinProduct() *ShopMcoinProduct {
	if x != nil {
		return x.McoinProduct
	}
	return nil
}

func (x *RechargeReq) GetConcertProduct() *ShopConcertProduct {
	if x != nil {
		return x.ConcertProduct
	}
	return nil
}

type RechargeRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Retcode          int32  `protobuf:"varint,12,opt,name=retcode,proto3" json:"retcode,omitempty"`
	IsShowMinorsHint bool   `protobuf:"varint,6,opt,name=is_show_minors_hint,json=isShowMinorsHint,proto3" json:"is_show_minors_hint,omitempty"`
	ProductId        string `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
}

func (x *RechargeRsp) Reset() {
	*x = RechargeRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_cmd_recharge_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RechargeRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RechargeRsp) ProtoMessage() {}

func (x *RechargeRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_cmd_recharge_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RechargeRsp.ProtoReflect.Descriptor instead.
func (*RechargeRsp) Descriptor() ([]byte, []int) {
	return file_cmd_cmd_recharge_proto_rawDescGZIP(), []int{1}
}

func (x *RechargeRsp) GetRetcode() int32 {
	if x != nil {
		return x.Retcode
	}
	return 0
}

func (x *RechargeRsp) GetIsShowMinorsHint() bool {
	if x != nil {
		return x.IsShowMinorsHint
	}
	return false
}

func (x *RechargeRsp) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

type OrderFinishNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderId               uint32       `protobuf:"varint,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	CardProductRemainDays uint32       `protobuf:"varint,15,opt,name=card_product_remain_days,json=cardProductRemainDays,proto3" json:"card_product_remain_days,omitempty"`
	ItemList              []*ItemParam `protobuf:"bytes,9,rep,name=item_list,json=itemList,proto3" json:"item_list,omitempty"`
	AddMcoin              uint32       `protobuf:"varint,7,opt,name=add_mcoin,json=addMcoin,proto3" json:"add_mcoin,omitempty"`
	ProductId             string       `protobuf:"bytes,6,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
}

func (x *OrderFinishNotify) Reset() {
	*x = OrderFinishNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_cmd_recharge_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderFinishNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderFinishNotify) ProtoMessage() {}

func (x *OrderFinishNotify) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_cmd_recharge_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderFinishNotify.ProtoReflect.Descriptor instead.
func (*OrderFinishNotify) Descriptor() ([]byte, []int) {
	return file_cmd_cmd_recharge_proto_rawDescGZIP(), []int{2}
}

func (x *OrderFinishNotify) GetOrderId() uint32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *OrderFinishNotify) GetCardProductRemainDays() uint32 {
	if x != nil {
		return x.CardProductRemainDays
	}
	return 0
}

func (x *OrderFinishNotify) GetItemList() []*ItemParam {
	if x != nil {
		return x.ItemList
	}
	return nil
}

func (x *OrderFinishNotify) GetAddMcoin() uint32 {
	if x != nil {
		return x.AddMcoin
	}
	return 0
}

func (x *OrderFinishNotify) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

type CardProductRewardNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hcoin      uint32 `protobuf:"varint,6,opt,name=hcoin,proto3" json:"hcoin,omitempty"`
	ProductId  string `protobuf:"bytes,14,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	RemainDays uint32 `protobuf:"varint,1,opt,name=remain_days,json=remainDays,proto3" json:"remain_days,omitempty"`
}

func (x *CardProductRewardNotify) Reset() {
	*x = CardProductRewardNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_cmd_recharge_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CardProductRewardNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardProductRewardNotify) ProtoMessage() {}

func (x *CardProductRewardNotify) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_cmd_recharge_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardProductRewardNotify.ProtoReflect.Descriptor instead.
func (*CardProductRewardNotify) Descriptor() ([]byte, []int) {
	return file_cmd_cmd_recharge_proto_rawDescGZIP(), []int{3}
}

func (x *CardProductRewardNotify) GetHcoin() uint32 {
	if x != nil {
		return x.Hcoin
	}
	return 0
}

func (x *CardProductRewardNotify) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *CardProductRewardNotify) GetRemainDays() uint32 {
	if x != nil {
		return x.RemainDays
	}
	return 0
}

type ProductPriceTier struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProductId string `protobuf:"bytes,6,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	PriceTier string `protobuf:"bytes,12,opt,name=price_tier,json=priceTier,proto3" json:"price_tier,omitempty"`
}

func (x *ProductPriceTier) Reset() {
	*x = ProductPriceTier{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_cmd_recharge_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductPriceTier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductPriceTier) ProtoMessage() {}

func (x *ProductPriceTier) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_cmd_recharge_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductPriceTier.ProtoReflect.Descriptor instead.
func (*ProductPriceTier) Descriptor() ([]byte, []int) {
	return file_cmd_cmd_recharge_proto_rawDescGZIP(), []int{4}
}

func (x *ProductPriceTier) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ProductPriceTier) GetPriceTier() string {
	if x != nil {
		return x.PriceTier
	}
	return ""
}

type ResinCardData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RemainRewardDays    uint32 `protobuf:"varint,3,opt,name=remain_reward_days,json=remainRewardDays,proto3" json:"remain_reward_days,omitempty"`
	ExpireTime          uint32 `protobuf:"varint,12,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"`
	LastDailyRewardTime uint32 `protobuf:"varint,2,opt,name=last_daily_reward_time,json=lastDailyRewardTime,proto3" json:"last_daily_reward_time,omitempty"`
	ConfigId            uint32 `protobuf:"varint,7,opt,name=config_id,json=configId,proto3" json:"config_id,omitempty"`
}

func (x *ResinCardData) Reset() {
	*x = ResinCardData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_cmd_recharge_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResinCardData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResinCardData) ProtoMessage() {}

func (x *ResinCardData) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_cmd_recharge_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResinCardData.ProtoReflect.Descriptor instead.
func (*ResinCardData) Descriptor() ([]byte, []int) {
	return file_cmd_cmd_recharge_proto_rawDescGZIP(), []int{5}
}

func (x *ResinCardData) GetRemainRewardDays() uint32 {
	if x != nil {
		return x.RemainRewardDays
	}
	return 0
}

func (x *ResinCardData) GetExpireTime() uint32 {
	if x != nil {
		return x.ExpireTime
	}
	return 0
}

func (x *ResinCardData) GetLastDailyRewardTime() uint32 {
	if x != nil {
		return x.LastDailyRewardTime
	}
	return 0
}

func (x *ResinCardData) GetConfigId() uint32 {
	if x != nil {
		return x.ConfigId
	}
	return 0
}

type PlayerRechargeDataNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CardProductRemainDays uint32              `protobuf:"varint,12,opt,name=card_product_remain_days,json=cardProductRemainDays,proto3" json:"card_product_remain_days,omitempty"`
	ProductPriceTierList  []*ProductPriceTier `protobuf:"bytes,11,rep,name=product_price_tier_list,json=productPriceTierList,proto3" json:"product_price_tier_list,omitempty"`
}

func (x *PlayerRechargeDataNotify) Reset() {
	*x = PlayerRechargeDataNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_cmd_recharge_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerRechargeDataNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerRechargeDataNotify) ProtoMessage() {}

func (x *PlayerRechargeDataNotify) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_cmd_recharge_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerRechargeDataNotify.ProtoReflect.Descriptor instead.
func (*PlayerRechargeDataNotify) Descriptor() ([]byte, []int) {
	return file_cmd_cmd_recharge_proto_rawDescGZIP(), []int{6}
}

func (x *PlayerRechargeDataNotify) GetCardProductRemainDays() uint32 {
	if x != nil {
		return x.CardProductRemainDays
	}
	return 0
}

func (x *PlayerRechargeDataNotify) GetProductPriceTierList() []*ProductPriceTier {
	if x != nil {
		return x.ProductPriceTierList
	}
	return nil
}

type OrderDisplayNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderId uint32 `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
}

func (x *OrderDisplayNotify) Reset() {
	*x = OrderDisplayNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_cmd_recharge_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderDisplayNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderDisplayNotify) ProtoMessage() {}

func (x *OrderDisplayNotify) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_cmd_recharge_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderDisplayNotify.ProtoReflect.Descriptor instead.
func (*OrderDisplayNotify) Descriptor() ([]byte, []int) {
	return file_cmd_cmd_recharge_proto_rawDescGZIP(), []int{7}
}

func (x *OrderDisplayNotify) GetOrderId() uint32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type ReportTrackingIOInfoNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rydevicetype string `protobuf:"bytes,12,opt,name=rydevicetype,proto3" json:"rydevicetype,omitempty"`
	Deviceid     string `protobuf:"bytes,1,opt,name=deviceid,proto3" json:"deviceid,omitempty"`
	ClientTz     string `protobuf:"bytes,13,opt,name=client_tz,json=clientTz,proto3" json:"client_tz,omitempty"`
	Appid        string `protobuf:"bytes,14,opt,name=appid,proto3" json:"appid,omitempty"`
	Mac          string `protobuf:"bytes,15,opt,name=mac,proto3" json:"mac,omitempty"`
}

func (x *ReportTrackingIOInfoNotify) Reset() {
	*x = ReportTrackingIOInfoNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_cmd_recharge_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReportTrackingIOInfoNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportTrackingIOInfoNotify) ProtoMessage() {}

func (x *ReportTrackingIOInfoNotify) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_cmd_recharge_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportTrackingIOInfoNotify.ProtoReflect.Descriptor instead.
func (*ReportTrackingIOInfoNotify) Descriptor() ([]byte, []int) {
	return file_cmd_cmd_recharge_proto_rawDescGZIP(), []int{8}
}

func (x *ReportTrackingIOInfoNotify) GetRydevicetype() string {
	if x != nil {
		return x.Rydevicetype
	}
	return ""
}

func (x *ReportTrackingIOInfoNotify) GetDeviceid() string {
	if x != nil {
		return x.Deviceid
	}
	return ""
}

func (x *ReportTrackingIOInfoNotify) GetClientTz() string {
	if x != nil {
		return x.ClientTz
	}
	return ""
}

func (x *ReportTrackingIOInfoNotify) GetAppid() string {
	if x != nil {
		return x.Appid
	}
	return ""
}

func (x *ReportTrackingIOInfoNotify) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

type TakeResinCardDailyRewardReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProductConfigId uint32 `protobuf:"varint,14,opt,name=product_config_id,json=productConfigId,proto3" json:"product_config_id,omitempty"`
}

func (x *TakeResinCardDailyRewardReq) Reset() {
	*x = TakeResinCardDailyRewardReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_cmd_recharge_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TakeResinCardDailyRewardReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TakeResinCardDailyRewardReq) ProtoMessage() {}

func (x *TakeResinCardDailyRewardReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_cmd_recharge_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TakeResinCardDailyRewardReq.ProtoReflect.Descriptor instead.
func (*TakeResinCardDailyRewardReq) Descriptor() ([]byte, []int) {
	return file_cmd_cmd_recharge_proto_rawDescGZIP(), []int{9}
}

func (x *TakeResinCardDailyRewardReq) GetProductConfigId() uint32 {
	if x != nil {
		return x.ProductConfigId
	}
	return 0
}

type TakeResinCardDailyRewardRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemVec         []*ItemParam `protobuf:"bytes,6,rep,name=item_vec,json=itemVec,proto3" json:"item_vec,omitempty"`
	Retcode         int32        `protobuf:"varint,4,opt,name=retcode,proto3" json:"retcode,omitempty"`
	ProductConfigId uint32       `protobuf:"varint,12,opt,name=product_config_id,json=productConfigId,proto3" json:"product_config_id,omitempty"`
}

func (x *TakeResinCardDailyRewardRsp) Reset() {
	*x = TakeResinCardDailyRewardRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_cmd_recharge_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TakeResinCardDailyRewardRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TakeResinCardDailyRewardRsp) ProtoMessage() {}

func (x *TakeResinCardDailyRewardRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_cmd_recharge_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TakeResinCardDailyRewardRsp.ProtoReflect.Descriptor instead.
func (*TakeResinCardDailyRewardRsp) Descriptor() ([]byte, []int) {
	return file_cmd_cmd_recharge_proto_rawDescGZIP(), []int{10}
}

func (x *TakeResinCardDailyRewardRsp) GetItemVec() []*ItemParam {
	if x != nil {
		return x.ItemVec
	}
	return nil
}

func (x *TakeResinCardDailyRewardRsp) GetRetcode() int32 {
	if x != nil {
		return x.Retcode
	}
	return 0
}

func (x *TakeResinCardDailyRewardRsp) GetProductConfigId() uint32 {
	if x != nil {
		return x.ProductConfigId
	}
	return 0
}

type ResinCardDataUpdateNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TodayStartTime uint32           `protobuf:"varint,6,opt,name=today_start_time,json=todayStartTime,proto3" json:"today_start_time,omitempty"`
	CardDataList   []*ResinCardData `protobuf:"bytes,2,rep,name=card_data_list,json=cardDataList,proto3" json:"card_data_list,omitempty"`
}

func (x *ResinCardDataUpdateNotify) Reset() {
	*x = ResinCardDataUpdateNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_cmd_recharge_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResinCardDataUpdateNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResinCardDataUpdateNotify) ProtoMessage() {}

func (x *ResinCardDataUpdateNotify) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_cmd_recharge_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResinCardDataUpdateNotify.ProtoReflect.Descriptor instead.
func (*ResinCardDataUpdateNotify) Descriptor() ([]byte, []int) {
	return file_cmd_cmd_recharge_proto_rawDescGZIP(), []int{11}
}

func (x *ResinCardDataUpdateNotify) GetTodayStartTime() uint32 {
	if x != nil {
		return x.TodayStartTime
	}
	return 0
}

func (x *ResinCardDataUpdateNotify) GetCardDataList() []*ResinCardData {
	if x != nil {
		return x.CardDataList
	}
	return nil
}

var File_cmd_cmd_recharge_proto protoreflect.FileDescriptor

var file_cmd_cmd_recharge_proto_rawDesc = []byte{
	0x0a, 0x16, 0x63, 0x6d, 0x64, 0x2f, 0x63, 0x6d, 0x64, 0x5f, 0x72, 0x65, 0x63, 0x68, 0x61, 0x72,
	0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x0c, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x81, 0x02,
	0x0a, 0x0b, 0x52, 0x65, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x52, 0x65, 0x71, 0x12, 0x35, 0x0a,
	0x0c, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6c, 0x61, 0x79,
	0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x0b, 0x70, 0x6c, 0x61, 0x79, 0x50, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x12, 0x39, 0x0a, 0x0c, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x70, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x53, 0x68, 0x6f, 0x70, 0x43, 0x61, 0x72, 0x64, 0x50, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x52, 0x0b, 0x63, 0x61, 0x72, 0x64, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x12,
	0x3c, 0x0a, 0x0d, 0x6d, 0x63, 0x6f, 0x69, 0x6e, 0x5f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x18, 0x0e, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53,
	0x68, 0x6f, 0x70, 0x4d, 0x63, 0x6f, 0x69, 0x6e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52,
	0x0c, 0x6d, 0x63, 0x6f, 0x69, 0x6e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x12, 0x42, 0x0a,
	0x0f, 0x63, 0x6f, 0x6e, 0x63, 0x65, 0x72, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53,
	0x68, 0x6f, 0x70, 0x43, 0x6f, 0x6e, 0x63, 0x65, 0x72, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x52, 0x0e, 0x63, 0x6f, 0x6e, 0x63, 0x65, 0x72, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x22, 0x75, 0x0a, 0x0b, 0x52, 0x65, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x52, 0x73, 0x70,
	0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x74, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x07, 0x72, 0x65, 0x74, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x2d, 0x0a, 0x13, 0x69, 0x73,
	0x5f, 0x73, 0x68, 0x6f, 0x77, 0x5f, 0x6d, 0x69, 0x6e, 0x6f, 0x72, 0x73, 0x5f, 0x68, 0x69, 0x6e,
	0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x10, 0x69, 0x73, 0x53, 0x68, 0x6f, 0x77, 0x4d,
	0x69, 0x6e, 0x6f, 0x72, 0x73, 0x48, 0x69, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x22, 0xd2, 0x01, 0x0a, 0x11, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x19,
	0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x37, 0x0a, 0x18, 0x63, 0x61, 0x72,
	0x64, 0x5f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e,
	0x5f, 0x64, 0x61, 0x79, 0x73, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x15, 0x63, 0x61, 0x72,
	0x64, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x44, 0x61,
	0x79, 0x73, 0x12, 0x2d, 0x0a, 0x09, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18,
	0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x74,
	0x65, 0x6d, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x52, 0x08, 0x69, 0x74, 0x65, 0x6d, 0x4c, 0x69, 0x73,
	0x74, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x64, 0x64, 0x5f, 0x6d, 0x63, 0x6f, 0x69, 0x6e, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x61, 0x64, 0x64, 0x4d, 0x63, 0x6f, 0x69, 0x6e, 0x12, 0x1d,
	0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x22, 0x6f, 0x0a,
	0x17, 0x43, 0x61, 0x72, 0x64, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x65, 0x77, 0x61,
	0x72, 0x64, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x68, 0x63, 0x6f, 0x69,
	0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x68, 0x63, 0x6f, 0x69, 0x6e, 0x12, 0x1d,
	0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x0e, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x12, 0x1f, 0x0a,
	0x0b, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x5f, 0x64, 0x61, 0x79, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x0a, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x44, 0x61, 0x79, 0x73, 0x22, 0x50,
	0x0a, 0x10, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x54, 0x69,
	0x65, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49,
	0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x69, 0x63, 0x65, 0x5f, 0x74, 0x69, 0x65, 0x72, 0x18,
	0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x69, 0x63, 0x65, 0x54, 0x69, 0x65, 0x72,
	0x22, 0xb0, 0x01, 0x0a, 0x0d, 0x52, 0x65, 0x73, 0x69, 0x6e, 0x43, 0x61, 0x72, 0x64, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x2c, 0x0a, 0x12, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x5f, 0x72, 0x65, 0x77,
	0x61, 0x72, 0x64, 0x5f, 0x64, 0x61, 0x79, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x10,
	0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x44, 0x61, 0x79, 0x73,
	0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18,
	0x0c, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x54, 0x69, 0x6d,
	0x65, 0x12, 0x33, 0x0a, 0x16, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x64, 0x61, 0x69, 0x6c, 0x79, 0x5f,
	0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x13, 0x6c, 0x61, 0x73, 0x74, 0x44, 0x61, 0x69, 0x6c, 0x79, 0x52, 0x65, 0x77, 0x61,
	0x72, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x5f, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x49, 0x64, 0x22, 0xa3, 0x01, 0x0a, 0x18, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x65,
	0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x44, 0x61, 0x74, 0x61, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79,
	0x12, 0x37, 0x0a, 0x18, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x5f, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x5f, 0x64, 0x61, 0x79, 0x73, 0x18, 0x0c, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x15, 0x63, 0x61, 0x72, 0x64, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52,
	0x65, 0x6d, 0x61, 0x69, 0x6e, 0x44, 0x61, 0x79, 0x73, 0x12, 0x4e, 0x0a, 0x17, 0x70, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x5f, 0x74, 0x69, 0x65, 0x72, 0x5f,
	0x6c, 0x69, 0x73, 0x74, 0x18, 0x0b, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x54,
	0x69, 0x65, 0x72, 0x52, 0x14, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x50, 0x72, 0x69, 0x63,
	0x65, 0x54, 0x69, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x2f, 0x0a, 0x12, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x44, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12,
	0x19, 0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x22, 0xa1, 0x01, 0x0a, 0x1a, 0x52,
	0x65, 0x70, 0x6f, 0x72, 0x74, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x49, 0x4f, 0x49,
	0x6e, 0x66, 0x6f, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x22, 0x0a, 0x0c, 0x72, 0x79, 0x64,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x74, 0x79, 0x70, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x72, 0x79, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x5f, 0x74, 0x7a, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x54, 0x7a, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x70, 0x70, 0x69, 0x64, 0x18,
	0x0e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x70, 0x70, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03,
	0x6d, 0x61, 0x63, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x61, 0x63, 0x22, 0x49,
	0x0a, 0x1b, 0x54, 0x61, 0x6b, 0x65, 0x52, 0x65, 0x73, 0x69, 0x6e, 0x43, 0x61, 0x72, 0x64, 0x44,
	0x61, 0x69, 0x6c, 0x79, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x12, 0x2a, 0x0a,
	0x11, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x5f,
	0x69, 0x64, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x64, 0x22, 0x90, 0x01, 0x0a, 0x1b, 0x54, 0x61,
	0x6b, 0x65, 0x52, 0x65, 0x73, 0x69, 0x6e, 0x43, 0x61, 0x72, 0x64, 0x44, 0x61, 0x69, 0x6c, 0x79,
	0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x52, 0x73, 0x70, 0x12, 0x2b, 0x0a, 0x08, 0x69, 0x74, 0x65,
	0x6d, 0x5f, 0x76, 0x65, 0x63, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x52, 0x07, 0x69,
	0x74, 0x65, 0x6d, 0x56, 0x65, 0x63, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x74, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x72, 0x65, 0x74, 0x63, 0x6f, 0x64, 0x65,
	0x12, 0x2a, 0x0a, 0x11, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x63, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0f, 0x70, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x64, 0x22, 0x81, 0x01, 0x0a,
	0x19, 0x52, 0x65, 0x73, 0x69, 0x6e, 0x43, 0x61, 0x72, 0x64, 0x44, 0x61, 0x74, 0x61, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x28, 0x0a, 0x10, 0x74, 0x6f,
	0x64, 0x61, 0x79, 0x5f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x0e, 0x74, 0x6f, 0x64, 0x61, 0x79, 0x53, 0x74, 0x61, 0x72, 0x74,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x3a, 0x0a, 0x0e, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x64, 0x61, 0x74,
	0x61, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x69, 0x6e, 0x43, 0x61, 0x72, 0x64, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x0c, 0x63, 0x61, 0x72, 0x64, 0x44, 0x61, 0x74, 0x61, 0x4c, 0x69, 0x73, 0x74,
	0x42, 0x28, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74,
	0x65, 0x79, 0x76, 0x61, 0x74, 0x2d, 0x68, 0x65, 0x6c, 0x70, 0x65, 0x72, 0x2f, 0x68, 0x6b, 0x34,
	0x65, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_cmd_cmd_recharge_proto_rawDescOnce sync.Once
	file_cmd_cmd_recharge_proto_rawDescData = file_cmd_cmd_recharge_proto_rawDesc
)

func file_cmd_cmd_recharge_proto_rawDescGZIP() []byte {
	file_cmd_cmd_recharge_proto_rawDescOnce.Do(func() {
		file_cmd_cmd_recharge_proto_rawDescData = protoimpl.X.CompressGZIP(file_cmd_cmd_recharge_proto_rawDescData)
	})
	return file_cmd_cmd_recharge_proto_rawDescData
}

var file_cmd_cmd_recharge_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_cmd_cmd_recharge_proto_goTypes = []interface{}{
	(*RechargeReq)(nil),                 // 0: proto.RechargeReq
	(*RechargeRsp)(nil),                 // 1: proto.RechargeRsp
	(*OrderFinishNotify)(nil),           // 2: proto.OrderFinishNotify
	(*CardProductRewardNotify)(nil),     // 3: proto.CardProductRewardNotify
	(*ProductPriceTier)(nil),            // 4: proto.ProductPriceTier
	(*ResinCardData)(nil),               // 5: proto.ResinCardData
	(*PlayerRechargeDataNotify)(nil),    // 6: proto.PlayerRechargeDataNotify
	(*OrderDisplayNotify)(nil),          // 7: proto.OrderDisplayNotify
	(*ReportTrackingIOInfoNotify)(nil),  // 8: proto.ReportTrackingIOInfoNotify
	(*TakeResinCardDailyRewardReq)(nil), // 9: proto.TakeResinCardDailyRewardReq
	(*TakeResinCardDailyRewardRsp)(nil), // 10: proto.TakeResinCardDailyRewardRsp
	(*ResinCardDataUpdateNotify)(nil),   // 11: proto.ResinCardDataUpdateNotify
	(*PlayProduct)(nil),                 // 12: proto.PlayProduct
	(*ShopCardProduct)(nil),             // 13: proto.ShopCardProduct
	(*ShopMcoinProduct)(nil),            // 14: proto.ShopMcoinProduct
	(*ShopConcertProduct)(nil),          // 15: proto.ShopConcertProduct
	(*ItemParam)(nil),                   // 16: proto.ItemParam
}
var file_cmd_cmd_recharge_proto_depIdxs = []int32{
	12, // 0: proto.RechargeReq.play_product:type_name -> proto.PlayProduct
	13, // 1: proto.RechargeReq.card_product:type_name -> proto.ShopCardProduct
	14, // 2: proto.RechargeReq.mcoin_product:type_name -> proto.ShopMcoinProduct
	15, // 3: proto.RechargeReq.concert_product:type_name -> proto.ShopConcertProduct
	16, // 4: proto.OrderFinishNotify.item_list:type_name -> proto.ItemParam
	4,  // 5: proto.PlayerRechargeDataNotify.product_price_tier_list:type_name -> proto.ProductPriceTier
	16, // 6: proto.TakeResinCardDailyRewardRsp.item_vec:type_name -> proto.ItemParam
	5,  // 7: proto.ResinCardDataUpdateNotify.card_data_list:type_name -> proto.ResinCardData
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_cmd_cmd_recharge_proto_init() }
func file_cmd_cmd_recharge_proto_init() {
	if File_cmd_cmd_recharge_proto != nil {
		return
	}
	file_define_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_cmd_cmd_recharge_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RechargeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_cmd_recharge_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RechargeRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_cmd_recharge_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderFinishNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_cmd_recharge_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CardProductRewardNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_cmd_recharge_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductPriceTier); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_cmd_recharge_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResinCardData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_cmd_recharge_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerRechargeDataNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_cmd_recharge_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderDisplayNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_cmd_recharge_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReportTrackingIOInfoNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_cmd_recharge_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TakeResinCardDailyRewardReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_cmd_recharge_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TakeResinCardDailyRewardRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_cmd_recharge_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResinCardDataUpdateNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cmd_cmd_recharge_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cmd_cmd_recharge_proto_goTypes,
		DependencyIndexes: file_cmd_cmd_recharge_proto_depIdxs,
		MessageInfos:      file_cmd_cmd_recharge_proto_msgTypes,
	}.Build()
	File_cmd_cmd_recharge_proto = out.File
	file_cmd_cmd_recharge_proto_rawDesc = nil
	file_cmd_cmd_recharge_proto_goTypes = nil
	file_cmd_cmd_recharge_proto_depIdxs = nil
}
